### PR TITLE
Fix #16336 - Correct a segfault

### LINKED ISSUE #16336: segfault with `tc struct`
I found this one when writing the bug report for #16335 .

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch x86_64
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     |  radare2 4.3.1 0 @ linux-x86-64 git.4.3.1 commit: unknown build: 2020-03-20__16:02:58

### Expected behavior
No segfault

### Actual behavior
Segmentation fault.

### Steps to reproduce the behavior 
```
r2 -
tc struct
```

### PR DESCRIPTION
**Pull request by mdolmen**
* Change a condition returning always true even when it shouldn't
* Correct typos in tc help

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Segmentation fault when using `tc struct`. The expected command looks like `tc struct.foo`.

**Test plan**

`tc struct` should not triggers a segmentation fault.

**Closing issues**

Closes #16336.

### CODE REVIEW

File: libr/core/cmd_type.c [hunk 1]
```diff
@@ -1060,8 +1060,9 @@ static int cmd_type(void *data, const char *input) {
 			break;
 		case ' ': {
 			const char *type = r_str_trim_head_ro (input + 1);
-			const char *name = type ? strchr (type, '.') + 1: NULL;
+			const char *name = type ? strchr (type, '.') : NULL;
 			if (name && type) {
+                name++; // skip the '.'
```
Comment (radare) [inline libr/core/cmd_type.c]: Use tabs
