### PR TITLE
Fix invalid mem free when one DIE has two or more DW_AT_name attributes ##bin #25537

### LINKED ISSUE #25537: Invalid memory free when one DIE has two or more DW_AT_name attributes
## Environment
```
r2r 6.1.1 +35386 abi:74 @ linux-x86_64
birth: git.6.1.0-122-gaf5cd396ba 2026-03-09__07:07:24
commit: af5cd396bac433b562d4be021af4ea0505848b50
options: gpl -O? cs:5 cl:2 make
```
### OS/arch/bits
Linux archlinux 6.15.9-arch1-1 x86_64
### File format of the file you reverse
ELF
### Architecture/bits of the file
x86/32, x86/64
### Git commit used
2cf6931a4fa55ec3b98cfa124d734f35d5473dd6

### Expected behavior
```
$ radare2 -AA ./test.poc
```
Analyzes the file and returns a shell to the user.

### Actual behavior
```
$ radare2 -AA ./test.poc
free(): invalid pointer
```
### Backtrace:
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=0x6, no_tid=no_tid@entry=0x0) at pthread_kill.c:44
#1  0x00007ffff7e1987f in __pthread_kill_internal (threadid=<optimized out>, signo=0x6) at pthread_kill.c:89
#2  0x00007ffff7dc4ec2 in __GI_raise (sig=sig@entry=0x6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7dadf28 in __GI_abort () at abort.c:77
#4  0x00007ffff7daeedc in __libc_message_impl (vma_name=vma_name@entry=0x7ffff7f24f89 "glibc: fatal", fmt=fmt@entry=0x7ffff7f2858d "%s\n") at ../sysdeps/posix/libc_fatal.c:138
#5  0x00007ffff7e22d3c in __libc_message_wrapper (vmaname=0x7ffff7f24f89 "glibc: fatal", fmt=0x7ffff7f2858d "%s\n") at ../include/stdio.h:203
#6  malloc_printerr (str=<optimized out>) at malloc.c:5359
#7  0x00007ffff7e22d51 in malloc_printerr_tail (str=<optimized out>) at malloc.c:5376
#8  0x00007ffff7387b6f in parse_atomic_type (ctx=0x7fffffffd6c0, idx=0x6) at dwarf_process.c:750
#9  0x00007ffff738c63f in parse_type_entry (ctx=0x7fffffffd6c0, idx=0x6) at dwarf_process.c:1973
#10 0x00007ffff738c78c in r_anal_dwarf_process_info (anal=0x555555576b40, ctx=0x7fffffffd760) at dwarf_process.c:2012
#11 0x00007ffff760bf95 in bin_addrline (core=0x7ffff5f39010, pj=0x0, mode=0x2) at cbin.c:1158
#12 0x00007ffff761dd2e in r_core_bin_info (core=0x7ffff5f39010, action=0xd04fff, pj=0x0, mode=0x2, va=0x1, filter=0x0, chksum=0x0) at cbin.c:5060
#13 0x00007ffff7608797 in r_core_bin_set_env (core=0x7ffff5f39010, binfile=0x7ffff5ef8028) at cbin.c:314
#14 0x00007ffff75bfb4d in r_core_file_load_for_io_plugin (r=0x7ffff5f39010, baseaddr=0xffffffffffffffff, loadaddr=0x0) at cfile.c:490
#15 0x00007ffff75c05fa in r_core_bin_load (r=0x7ffff5f39010, filenameuri=0x55555563f760 "/home/alex/software/projects/fuzzing/workdir/_evil_inputs/610/crash/input_a",
   baddr=0xffffffffffffffff) at cfile.c:740
#16 0x00007ffff79e08dc in binload (r=0x7ffff5f39010, filepath=0x55555563f760 "/home/alex/software/projects/fuzzing/workdir/_evil_inputs/610/crash/input_a", baddr=0xffffffffffffffff)
   at radare2.c:618
#17 0x00007ffff79e4343 in r_main_radare2 (argc=0x5, argv=0x7fffffffe0b8) at radare2.c:1613
#18 0x0000555555555713 in main (argc=0x5, argv=0x7fffffffe0b8) at radare2.c:119
#19 0x00007ffff7dafba7 in __libc_start_call_main (main=main@entry=0x555555555567 <main>, argc=argc@entry=0x5, argv=argv@entry=0x7fffffffe0b8) at ../sysdeps/nptl/libc_start_call_main.h:59
#20 0x00007ffff7dafcc7 in __libc_start_main_impl (main=0x555555555567 <main>, argc=0x5, argv=0x7fffffffe0b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
   stack_end=0x7fffffffe0a8) at ../csu/libc-start.c:360
#21 0x0000555555555141 in _start ()
```

## Test
Any elf x86_32/64 can be converted with the script:
```python
import os
import base64
import struct
import argparse
from elftools.elf.elffile import ELFFile

is64bit = False
outfiledes = None
tempfile="/tmp/debug_poc"
sections = {
    '.debug_info': 'YQAAAAUAAQgAAAAAARMAAAAdQQAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAvoAAAABUwFQEAAAAAAAABcAAAAAAAAAAZxdAAAAAwAAAAABXhBdAAAAEgAAAAwAAAAABAQHBgAAAAB7AAAABQABCEwAAAABAAwAAQgAAABjAAAAAgE6AAAACAAAAEEAAAACAzIAAAAABQKhAAM/AAAABEMAAAAQJwAFBAQIBgUIBwcBOgAAAAFXCAAHegAAAAgCIAAAAAkACgAJegAAAAAKbQAAAAMACwYBkgF2AAAABQcFCAUJBQQA',
    '.debug_abbrev': 'AREBJQ4TCwMfGx9VFxEBEBcAAAIuAQMOOgs7CzkLJxkRARIHQBh6GQETAAADNAADDjoLOws5C0kTAhe3QhcAAAQkAAsLPgsDDgAAAAERASUlEwUDJXIXEBcbJREbEgZzF4wBFwAAAjQAAyVJEz8ZOgs7CwIYAAADAQFJEwAABCEASRM3BQAABSQAAyU+CwsLAAAGJAADJQsLPgr///0uAREbEgZAGHoZAyU6CzsLSRM/GQAACAsBERsSBgAACTQAAiIDJToLOwtJEwAACkgAfxN9GwAACy4AAyU6CzsFJxlJEzwZPxkAAAA='
}
offsets = {}

def parse_args():
    p = argparse.ArgumentParser(description="Convert a file to PoC to crash radare2 version 6.0.8 or 6.1.0")
    p.add_argument("-f", "--file", 
        type=str, default="main",
        help="select the file to patch")
    return p.parse_args()

def copy(fname, oname):
    f = open(fname, "rb")
    w = open(oname, "wb")
    w.write(f.read())
    f.close()
    w.close()

def replace_section(outfile, name, b64data):
    f = open(tempfile, "wb")
    f.write(base64.b64decode(b64data))
    os.system(f"objcopy --remove-section {name} {outfile}")
    os.system(f"objcopy --add-section {name}={tempfile} --set-section-flags {name}=contents,debug {outfile}")
    f.close()

def get_section_header_offset(outelf, section_name):
    i = 0
    for sec in outelf.iter_sections():
        if sec.name == section_name:
            break
        i+=1
    return outelf._section_offset(i)

def patch_int_implementation(outfile, name, data, offset):
    shoff = offsets[name]
    outfiledes.seek(shoff+offset, 0)
    outfiledes.write(struct.pack("<I", data))

def patch_filesize(outfile, name, size):
    offs = 20
    if(is64bit):
        offs = 32
    patch_int_implementation(outfile, name, size, offs)

def patch_offset(outfile, name, length):
    offs = 16
    if(is64bit):
        offs = 24
    patch_int_implementation(outfile, name, length, offs)

def load_contents(outfile, name, b64data):
    barr = base64.b64decode(b64data)
    offset = outfiledes.seek(0, 2)
    filesize = len(barr)
    outfiledes.write(barr)
    patch_filesize(outfile, name, filesize)
    patch_offset(outfile, name, offset)

def load_offsets():
    global is64bit
    outfiledes.seek(0, 0)
    outfiledes.read(4)
    ei_class_value = int.from_bytes(outfiledes.read(1))
    if(ei_class_value == 2):
        is64bit = True
    outfiledes.seek(0, 0)
    outelf = ELFFile(outfiledes)
    for s in sections:
        offsets[s] = get_section_header_offset(outelf, s)


args = parse_args()
inpf = args.file
outf = f"{args.file}.poc"
copy(inpf, outf)
for s in sections:
    replace_section(outf, s, sections[s])
outfiledes = open(outf, "r+b")
load_offsets()
for s in sections:
    # need this bc objcopy does not feel like adding the data as well.
    load_contents(outf, s, sections[s])
```
To use simply run:
```
$ python poc.py -f <file>
```
And the targeted file will be patched to cause radare to abort/crash when analyzing.
Alternatively, I've also attached two test [files](https://github.com/user-attachments/files/25873454/files.zip), one for x86_64 and one for x86_32

## Analysis
Abort/Crash happens because the DWARF DIE (in the PoC provided it's at offset 0xA8) contains two or more DW_AT_name entries.  
In the PoC provided, the first DW_AT_name encountered, the code returns a string created with _**create_type_name_from_offset**_ (see **libr/anal/dwarf_process.c:753**), the second time a DW_AT_name is encountered, the arena allocated string is free'd which is incorrect.  
There are two cases, one where name points to a string inside of the arena, another where the string points inside en element in the _**RVecDwarfAttrValue**_ vector.  
In both cases, doing _R_FREE(name)_ ( **libr/anal/dwarf_process.c:750** ) is incorrect.  

### Affected versions
The bug was introduced with commit 1019c18ff6f373bf3bf0735c6e09729f578e242c and the affected versions are 6.0.8 and 6.1.0

## Fix suggestion
Since a call to free is wrong in both cases, the line R_FREE (name); can be removed. I will submit a patch immediately after i publish this issue.

### PR DESCRIPTION
**Pull request by AGhebrea**
- [X] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

Fixes #25537

## Analysis (Copied from issue description):
Abort/Crash happens because the DWARF DIE (in the PoC provided it's at offset 0xA8) contains two or more DW_AT_name entries.  
In the PoC provided, the first DW_AT_name encountered, the code returns a string created with _**create_type_name_from_offset**_ (see **libr/anal/dwarf_process.c:753**), the second time a DW_AT_name is encountered, the arena allocated string is free'd which is incorrect.  
There are two cases, one where name points to a string inside of the arena, another where the string points inside en element in the _**RVecDwarfAttrValue**_ vector.  
In both cases, doing R_FREE(name) ( **libr/anal/dwarf_process.c:750** ) is incorrect.

### CODE REVIEW

File: libr/anal/dwarf_process.c [hunk 1]
```diff
@@ -747,7 +747,6 @@ static void parse_atomic_type(Context *ctx, ut64 idx) {
 	R_VEC_FOREACH(die->attr_values, value) {
 		switch (value->attr_name) {
 		case DW_AT_name:
-			R_FREE (name);
```
Comment (trufae) [inline libr/anal/dwarf_process.c:750]: i think the R_FREE must be done inside the first if block. also swap the condition inside to be positive or well .we can just use the ternary operator

Comment (trufae) [reply libr/anal/dwarf_process.c:750]: otherwise it will be leaking memory. please update the pr with those changes and confirm there's no regression

Comment (AGhebrea) [reply libr/anal/dwarf_process.c:750]: Hello, we cannot R_FREE (name) because in both cases it points to non heap memory.  
I forgot to include this in the report, I double checked and the arena memory gets free'd in _r_arena_free_ ( **libr/anal/dwarf_process.c:2015** ). The vector memory gets free'd in _RVecDwarfAttrValue_free_ and _RVecDwarfAttrValue_fini_ ( **libr/bin/dwarf.c:1811** )
I also ran radare under valgrind as a sanity check and it reports no lost bytes. I believe that this is fine.

BTW, does the file/lineno information help or should i just remove it from subsequent issues/PRs ?

**Comment by trufae** [comment]
Oh I see now, yeah this was a leftover after an optimization made to reduce heap pressure. Good catch

**Comment by trufae** [comment]
Yep thats fine
