### PR TITLE
Fix a null deref in fcn_recurse ##anal

### LINKED ISSUE #15828: Invalid read and some uninitialized conditionals in r_anal_block_* (segfault)
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | Kernel Dump, vmlinux
| Architecture/bits of the file (mandatory)            | ARM 32 bit
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.2.0-git 23893 @ linux-x86-64 git.4.1.1-134-g9ddfafcd6 commit: 9ddfafcd652e9de3775e531a6f83fd2e914530d6 build: 2020-01-16__16:21:36

### Expected behavior
No crash
### Actual behavior

Dump of output (@ latest r2 9ddfafcd652e9de3775e531a6f83fd2e914530d6)

```
... Truncated symbol defines from r2pipe script
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[==500353== Conditional jump or move depends on uninitialised value(s)
==500353==    at 0x5FAC4E0: r_anal_block_split (block.c:304)
==500353==    by 0x5FA1465: fcn_recurse (fcn.c:499)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33DA: fcn_recurse (fcn.c:987)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353== 
==500353== Conditional jump or move depends on uninitialised value(s)
==500353==    at 0x5FA64FB: r_anal_bb_set_offset (bb.c:106)
==500353==    by 0x5FAC509: r_anal_block_split (block.c:307)
==500353==    by 0x5FA1465: fcn_recurse (fcn.c:499)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33DA: fcn_recurse (fcn.c:987)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353== 
==500353== Conditional jump or move depends on uninitialised value(s)
==500353==    at 0x5FAC4E0: r_anal_block_split (block.c:304)
==500353==    by 0x5FA1465: fcn_recurse (fcn.c:499)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA2F51: fcn_recurse (fcn.c:915)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33DA: fcn_recurse (fcn.c:987)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33DA: fcn_recurse (fcn.c:987)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33DA: fcn_recurse (fcn.c:987)
==500353== 
==500353== Invalid read of size 4
==500353==    at 0x5FAC7C8: r_anal_block_unref (block.c:362)
==500353==    by 0x5FA14C7: fcn_recurse (fcn.c:506)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33DA: fcn_recurse (fcn.c:987)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33DA: fcn_recurse (fcn.c:987)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==  Address 0xf0 is not stack'd, malloc'd or (recently) free'd
==500353== 
==500353== 
==500353== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==500353==  Access not within mapped region at address 0xF0
==500353==    at 0x5FAC7C8: r_anal_block_unref (block.c:362)
==500353==    by 0x5FA14C7: fcn_recurse (fcn.c:506)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33DA: fcn_recurse (fcn.c:987)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33DA: fcn_recurse (fcn.c:987)
==500353==    by 0x5FA4174: r_anal_fcn_bb (fcn.c:1206)
==500353==    by 0x5FA33A7: fcn_recurse (fcn.c:985)
==500353==  If you believe this happened as a result of a stack
==500353==  overflow in your program's main thread (unlikely but
==500353==  possible), you can try to increase the size of the
==500353==  main thread stack using the --main-stacksize= flag.
==500353==  The main thread stack size used in this run was 8388608.
==500353== 
==500353== HEAP SUMMARY:
==500353==     in use at exit: 89,574,438 bytes in 1,882,542 blocks
==500353==   total heap usage: 32,538,757 allocs, 30,656,215 frees, 6,110,772,421 bytes allocated
==500353== 
==500353== LEAK SUMMARY:
==500353==    definitely lost: 843,296 bytes in 56,218 blocks
==500353==    indirectly lost: 0 bytes in 0 blocks
==500353==      possibly lost: 2,667,869 bytes in 47,647 blocks
==500353==    still reachable: 86,063,273 bytes in 1,778,677 blocks
==500353==         suppressed: 0 bytes in 0 blocks
==500353== Rerun with --leak-check=full to see details of leaked memory
==500353== 
==500353== Use --track-origins=yes to see where uninitialised values come from
==500353== For lists of detected and suppressed errors, rerun with: -s
==500353== ERROR SUMMARY: 31 errors from 4 contexts (suppressed: 0 from 0)
./dor2.sh: line 2: 500353 Segmentation fault      (core dumped) valgrind r2 ./mtd4_unz -m 0xd0008000 -c '#!pipe python ./doitall.py'
```

Output (@ 14215350af35cc8b14710557c248d2e77baf380d) has the exact same output (line numbers didn't change, errors didn't change.)

### Steps to reproduce the behavior 

I've narrowed the guilty commit to 14215350af35cc8b14710557c248d2e77baf380d. Anything before it works fine.

I can't link the file or the r2pipe script I was using, but i was manually defining symbols at various addresses dumped from kallsyms. If you want me to test changes or do more research, please let me know.

### PR DESCRIPTION
**Pull request by thestr4ng3r**
Likely fixes_ #15828

### CODE REVIEW

File: libr/anal/fcn.c [hunk 1]
```diff
@@ -503,7 +503,9 @@ static int fcn_recurse(RAnal *anal, RAnalFunction *fcn, ut64 addr, ut64 len, int
 				fcn_takeover_block_recursive (fcn, existing_bb);
 			}
 		}
-		r_anal_block_unref (existing_bb);
+		if (existing_bb) {
```
Comment (radare) [inline libr/anal/fcn.c]: wtf? imho r_anal_block_unref should work like free(). accepting NULL as arg

Comment (thestr4ng3r) [reply libr/anal/fcn.c]: No. unref is not free, if you call unref and don't exactly know if it's NULL or not, you are doing something horribly wrong because a unref must always follow a corresponding ref.

**Comment by radare** [comment]
So i assume it is asserting. Right?

**Comment by thestr4ng3r** [comment]
It is asserting `block->ref > 0`, not NULL, but we can add it.

**Comment by radare** [comment]
yeah, will be good to have such assert
