### PR TITLE
Fix #21576 - Function stack frame size in case of FP register in a Thumb's PUSH ##analysis

### LINKED ISSUE #21576: Wrong function stack frame size in case of FP register in PUSH instruction (ARM).
## Environment

```sh
Tue 11 Apr 2023 10:25:44 AM MSK
radare2 5.8.3 30009 @ linux-x86-64 git.5.8.2-166-g91bbd79e1a
commit: 91bbd79e1a73115e9987c6da82f77799e5189206 build: 2023-02-28__10:57:51
Linux 5.10.0-21-amd64 x86_64
```

## Description

CPU Architecture: ARM.
Instruction Set: Thumb.

Size of registers stored onto stack by instruction PUSH is not counted in the function stack frame when FP register (r11) is the second in the list of registers. 

## Test

Correct stack frame size (12):

```sh
$ r2 malloc://32
[0x00000000]> e asm.arch=arm
[0x00000000]> e asm.bits=16
[0x00000000]> wx 2de9 8044 bde8 8044 7047 00bf
[0x00000000]> pi 3
push.w {r7, sl, lr}
pop.w {r7, sl, lr}
bx lr
[0x00000000]> af
[0x00000000]> afll
address    noret size  nbbs edges    cc cost  min bound range max bound  calls locals args xref frame name
========== ===== ===== ===== ===== ===== ==== ========== ===== ========== ===== ====== ==== ==== ===== ====
0x00000000     0   10     1     0     1    7 0x00000000    10 0x0000000a     0    0      0    0    12 fcn.00000000
```

Incorrect stack frame size (0):

```sh
$ r2 malloc://32
[0x00000000]> e asm.arch=arm
[0x00000000]> e asm.bits=16
[0x00000000]> wx 2de9 8048 bde8 8048 7047 00bf
[0x00000000]> pi 3
push.w {r7, fp, lr}
pop.w {r7, fp, lr}
bx lr
[0x00000000]> af
[0x00000000]> afll
address    noret size  nbbs edges    cc cost  min bound range max bound  calls locals args xref frame name
========== ===== ===== ===== ===== ===== ==== ========== ===== ========== ===== ====== ==== ==== ===== ====
0x00000000     0   10     1     0     1    7 0x00000000    10 0x0000000a     0    0      0    0     0 fcn.00000000
```

## Proposed Solution
Module: radare2\libr\anal\p\anal_arm_cs.c
The following piece of code contains "if" statement which overwrites 'stackop' attribute of PUSH instruction when FP is the second in the list of registers.

```c
...
	case ARM_INS_PUSH:
		op->stackop = R_ANAL_STACK_INC;
		op->stackptr = 4LL * insn->detail->arm.op_count;
		// fallthrough
	case ARM_INS_STM:
	case ARM_INS_STMDA:
	case ARM_INS_STMDB:
		op->type = R_ANAL_OP_TYPE_PUSH;
// 0x00008160    04202de5     str r2, [sp, -4]!
// 0x000082a0    28000be5     str r0, [fp, -0x28]
		if (REGBASE(1) == ARM_REG_FP) {
			op->stackop = R_ANAL_STACK_SET;
			op->stackptr = 0;
			op->ptr = MEMDISP(1);
		}
		break;
...
```

Possible solution: use additional condition for the "if" statement.

```c
...
	case ARM_INS_PUSH:
		op->stackop = R_ANAL_STACK_INC;
		op->stackptr = 4LL * insn->detail->arm.op_count;
		// fallthrough
	case ARM_INS_STM:
	case ARM_INS_STMDA:
	case ARM_INS_STMDB:
		op->type = R_ANAL_OP_TYPE_PUSH;
// 0x00008160    04202de5     str r2, [sp, -4]!
// 0x000082a0    28000be5     str r0, [fp, -0x28]
		if ((insn->id != ARM_INS_PUSH) && (REGBASE(1) == ARM_REG_FP)) {
			op->stackop = R_ANAL_STACK_SET;
			op->stackptr = 0;
			op->ptr = MEMDISP(1);
		}
		break;
...
```

### PR DESCRIPTION
**Pull request by AlexanderKucherov**
- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

Fix #21576

### CODE REVIEW

File: libr/anal/p/anal_arm_cs.c [hunk 1]
```diff
@@ -4049,7 +4049,7 @@ jmp $$ + 4 + ( [delta] * 2 )
 		op->type = R_ANAL_OP_TYPE_PUSH;
 // 0x00008160    04202de5     str r2, [sp, -4]!
 // 0x000082a0    28000be5     str r0, [fp, -0x28]
-		if (REGBASE(1) == ARM_REG_FP) {
+		if ((insn->id != ARM_INS_PUSH) && (REGBASE(1) == ARM_REG_FP)) {
```
Comment (trufae) [inline libr/anal/p/anal_arm_cs.c:4052]: i think its cleaner to remove the fallthrough case above and duplicate the code so the if can be removed here. it will be easier to read and easier to maintain. Can you do all those changes? if not i can handle that. thanks for submiting the PR, code changes are much easier to review like this

**Comment by AlexanderKucherov** [comment]
Yeah, this fix affected names of local variables in one of the existing tests. I've updated the failed test and added a new one.
Thanks for the support! Now I know how to execute the tests locally before submitting PR :)

File: libr/anal/p/anal_arm_cs.c (hunk 1 above)
Comment (AlexanderKucherov) [reply libr/anal/p/anal_arm_cs.c:4052]: Ok, clear.
Should I proceed with this PR or create a new one? Sorry, I've made too many commits for such a small fix :)
And yes, please feel free to update this PR as you need it, because I'm not so familiar with the code and with the process. I would appreciate your cooperation.

Comment (trufae) [reply libr/anal/p/anal_arm_cs.c:4052]: yep, do the change in this PR, sorry for the delay i was buried in meetings

Comment (trufae) [reply libr/anal/p/anal_arm_cs.c:4052]: i'll merge after that change :)

Comment (AlexanderKucherov) [reply libr/anal/p/anal_arm_cs.c]: That's fine :) I've just updated it. Could you please have a look once again when you get a minute?

**Comment by trufae** [comment]
Maybe you can be also interested in https://github.com/radareorg/radare2/pull/21257
