### PR TITLE
Automatically set the debug plugin when opening debug uris

### LINKED ISSUE #15399: Problem connecting to gdbserver using commands
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04 x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17284 @ darwin-x86-64 git.2.2.0-476-gf8cf84e06 commit: f8cf84e0653642d9ad34e760e0e56dd81860e799 build: 2018-02-17__11:08:27

### Expected behavior
```
radare2 -A ~/workspace/tests/main
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
 -- git checkout hamster
[0x00400a40]> o gdb://127.0.0.1:1234
= attach 50119 0
[0x00400af0]>
[0x00400af0]> dc
[0x7ffff7bbed2d]>
```

### Actual behavior
```
radare2 -A ~/workspace/tests/main
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
 -- The unix-like reverse engineering framework.
[0x00400a40]> o gdb://127.0.0.1:1234
= attach 50119 0
ptrace (PT_ATTACH): No such process
[0x00400af0]> dc
Cannot continue, run ood?
[0x00000000]>
```

#### Bypass

```
radare2 -A ~/workspace/tests/main
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
-- It's the year of desktop on radare2
[0x00400a40]> o gdb://127.0.0.1:1234
= attach 50119 0
ptrace (PT_ATTACH): No such process
[0x00400af0]> dL gdb
[0x00400af0]> o gdb://127.0.0.1:1234
= attach 50119 0
[0x00400af0]> dc
[0x7ffff7bbed2d]>
```

### Steps to reproduce the behavior 
- Run gdbserver on any binary `gdbserver :1234 /bin/ls`
- Connect in r2 with `o gdb://127.0.0.1:1234`
- Run `dc`
- It's possible to bypass this behavior using:
    -  `o gdb://127.0.0.1:1234`
    - `dL gdb`
    -  `o gdb://127.0.0.1:1234`

Notes: 
- Setting `dL gdb` before `o gdb://...` and/or running `o gdb://..` twice in a row doesn't help.
- Gdbserver sees the connection in the first try, it's just that the debugger isn't configured.

Didn't try reproducing on windows but it might be the same with windbg.

### PR DESCRIPTION
**Pull request by yossizap**
closes #15399 

Solves the gdbserver issue and fixes errors that might derive from forgetting `dL` or setting the wrong debug handler.

### CODE REVIEW

File: libr/core/cfile.c [hunk 1]
```diff
@@ -907,6 +907,12 @@ R_API RCoreFile *r_core_file_open(RCore *r, const char *file, int flags, ut64 lo
 			swstep = false;
 		}
 		r_config_set_i (r->config, "dbg.swstep", swstep);
+		// Set the correct debug handle
+		if (fd->plugin && fd->plugin->isdbg) {
+			const char *dh = strndup(file, (strstr(file, "://") - file));
```
Comment (radare) [inline libr/core/cfile.c]: What happens if theres no :// ?

Comment (yossizap) [reply libr/core/cfile.c]: Added a check. Is there a point in printing an error or attempting to set the current plugin's name as the debugger in case the uri didn't contain the debugger backend? Seems unlikely with fd->plugin->isdbg

File: libr/core/cfile.c [hunk 2]
```diff
@@ -907,6 +907,14 @@ R_API RCoreFile *r_core_file_open(RCore *r, const char *file, int flags, ut64 lo
 			swstep = false;
 		}
 		r_config_set_i (r->config, "dbg.swstep", swstep);
+		// Set the correct debug handle
+		if (fd->plugin && fd->plugin->isdbg) {
+			const char *dh = r_str_ndup (file, (strstr (file, "://") - file));
```
Comment (ret2libc) [inline libr/core/cfile.c]: if it's freed, it should not be `const char *`, I think.

Comment (ret2libc) [reply libr/core/cfile.c]: what if there is no `://` in `file`?

Comment (yossizap) [reply libr/core/cfile.c]: >if it's freed, it should not be const char *, I think.
Seems logical since you want to treat it as const, this is common practice with strdup but you can't control it's usage of malloc. I could explicitly cast the pointer down to char* when freeing or just remove const since it doesn't really matter.

>what if there is no :// in file?
Nothing is set since, as far as I know, it's not supposed to happen. Is there a valid uri that would set fd->plugin->isdbg to true without having ://? radare2.c does the same with -d

Comment (radare) [reply libr/core/cfile.c]: drop the const

File: libr/core/cfile.c [hunk 3]
```diff
@@ -907,6 +907,14 @@ R_API RCoreFile *r_core_file_open(RCore *r, const char *file, int flags, ut64 lo
...
+			if (dh) {
+				r_debug_use (r->dbg, dh);
+				free(dh);
```
Comment (radare) [inline libr/core/cfile.c]: imssing space before (
