### PR TITLE
Fix #16805 - Fix undefined behaviour in RAnalPlugin<arm.cs>.op()

### LINKED ISSUE #16805: `db/anal/arm ao 16 after ao 32` often fails on MacOS in GitHub Actions
The failure seems random, but happens quite often:
```
[XX] db/anal/arm ao 16 after ao 32
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e asm.bits=16
ao@0x50e
' bins/arm/elf/hello_world
-- stdout
--- .a	2020-05-11 09:01:06.000000000 +0000
+++ .b	2020-05-11 09:01:06.000000000 +0000
@@ -15,20 +15,3 @@
esil: 8,sp,-=,lr,r3,2,sp,=[*]
family: cpu
--
-address: 0x50e
-opcode: add r7, sp, 0
-disasm: add r7, sp, 0
-pseudo: r7 = sp + 0
-mnemonic: add
-description: add two values
-mask: ffff
-prefix: 0
-id: 2
-bytes: 00af
-refptr: 0
-size: 2
-sign: false
-type: add
-cycles: 1
-esil: 0,sp,+,0xffffffff,&,r7,=
-family: cpu
```
https://github.com/radareorg/radare2/runs/662640843#step:11:48

### PR DESCRIPTION
**Pull request by radare**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by radare** [comment]
The openbsd failure seems random

File: libr/anal/p/anal_arm_cs.c [hunk 1]
```diff
@@ -3520,6 +3520,9 @@ static ut8 *anal_mask(RAnal *anal, int size, const ut8 *data, ut64 at) {
 			break;
 		}
 		if (op->ptr != UT64_MAX || op->jump != UT64_MAX) {
+			if ((oplen * 8) > size - idx) {
```
Comment (xarkes) [inline libr/anal/p/anal_arm_cs.c:3523]: Why 8?

Comment (radare) [reply libr/anal/p/anal_arm_cs.c:3523]: see line below
