### PR TITLE
Fix #17494 - Pass the whole input string to r_core_cmd_str_pipe ##newshell

### LINKED ISSUE #17494: ?q/?+/?!-using test fails under newshell
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora Rawhide x86-64
| File format of the file you reverse (mandatory)      | Not applicable
| Architecture/bits of the file (mandatory)            | Not applicable
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 28339 @ linux-x86-64 git.4.4.0-572-g5f0be49fd commit: 5f0be49fd16fadb8c6338d0807f3de65c5fb1e0e build: 2020-08-19__21:51:33

### Expected behavior

After removing the `ARGS=-e cfg.newshell=false` from
https://github.com/radareorg/radare2/blob/5f0be49fd16fadb8c6338d0807f3de65c5fb1e0e/test/db/tools/r2#L111-L122
the test should pass after doing
```
R2_CFG_NEWSHELL=1 r2r -i db/tools/r2
```

### Actual behavior

q_test

It is likely the problem line is the first one:
```
?q `!!r2 -h~Usage?`
```

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

When executing a command like:
```
> ?e `!!r2 -h~Usage?`
```

One of the `!` was ignored, leading to the execution of different commands (`!r2 -h`was executed instead of `!!r2 -h`).

**Test plan**

The test should pass for both newshell and old.

**Closing issues**

Closes https://github.com/radareorg/radare2/issues/17494

### CODE REVIEW

File: libr/core/cmd.c [hunk 1]
```diff
@@ -4768,7 +4768,7 @@ static char *do_handle_substitution_cmd(struct tsr2cmd_state *state, TSNode inn_
 
 	// execute the sub command
 	char *o_out = inn_str[0] == '!'?
-		r_core_cmd_str_pipe (core, inn_str + 1):
+		r_core_cmd_str_pipe (core, inn_str):
```
Comment (kazarmy) [inline libr/core/cmd.c:4771]: isn't this the old parser?

Comment (ret2libc) [reply libr/core/cmd.c:4771]: fixed

**Review by kazarmy — APPROVED** [review]
lgtm
