### PR TITLE
Fix #21970 - Null checks in the R_LOG api ##crash

### LINKED ISSUE #21970: Null ptr in log.c
## TL;DR
we perfom a fuzz on radare2 and find this bug.
When rlog calls R_NEW0, it is not checked to see if memory space is alloced, and the pointer is referenced directly in the next line and outside the function.
https://github.com/radareorg/radare2/blob/a6edeac3d4467cf07c73855ca10616706f1a9cf4/libr/util/log.c#L29
## Log File
```
=================================================================
==21551==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7ffff7697341 bp 0x7ffff7801160 sp 0x7fffffffd870 T0)
==21551==The signal is caused by a WRITE memory access.
==21551==Hint: address points to the zero page.
    #0 0x7ffff7697341 in r_log_init /AFLFI/radare2/libr/util/log.c:30:15
    #1 0x7ffff7697341 in r_log_match /AFLFI/radare2/libr/util/log.c:102:2
    #2 0x7ffff76b21d1 in r_lib_opendir /AFLFI/radare2/libr/util/lib.c:429:3
    #3 0x7ffff7e5c9ef in __load_plugins /AFLFI/radare2/libr/main/rasm2.c:682:2
    #4 0x7ffff7e5c9ef in __as_new /AFLFI/radare2/libr/main/rasm2.c:41:4
    #5 0x7ffff7e5c9ef in r_main_rasm2 /AFLFI/radare2/libr/main/rasm2.c:750:18
    #6 0x7ffff7c04d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #7 0x7ffff7c04e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #8 0x5555555725b4 in _start (/AFLFI/radare2/binr/rasm2/rasm2+0x1e5b4) (BuildId: de5cd6211bd1e0fef359188b11fb03629176aab5)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /AFLFI/radare2/libr/util/log.c:30:15 in r_log_init
==21551==ABORTING
```

### PR DESCRIPTION
**Pull request by trufae**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

File: libr/util/log.c [hunk 1]
```diff
@@ -24,82 +24,98 @@ static const char *level_name(int i) {
...
+	}
 }
 
 R_API RLogLevel r_log_get_level(void) {
 	return rlog->level;
 }
 
 R_API RLogLevel r_log_get_traplevel(void) {
-	return rlog->traplevel;
+	return rlog? rlog->traplevel: R_LOG_LEVEL_FATAL;
```
Comment (trufae) [inline libr/util/log.c:60]:
```suggestion
	return rlog? rlog->traplevel: R_LOGLVL_FATAL;
```
