### PR TITLE
Fix #24989 - ARM RPI2 PE identification ##bin

### LINKED ISSUE #24989: pe.c - correct RPI2 machine type and misidentifying x86?
Regarding [`PE_IMAGE_FILE_MACHINE_RPI2`](https://github.com/radareorg/radare2/blob/a0cf3dbff497554ede095a3f53a762ac2ed23547/libr/bin/format/pe/pe.c#L10), added in 26dd53e, should this be 452 or 462?
The comments say 462 (0x01ce, which would make sense), and 452 is 0x014c which is the i386 machine type.

So it seems like https://github.com/radareorg/radare2/blob/a0cf3dbff497554ede095a3f53a762ac2ed23547/libr/bin/format/pe/pe.c#L3440 will incorrectly identify i386 machine type binaries as ARM?

### PR DESCRIPTION
**Pull request by trufae**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

File: libr/bin/format/pe/pe_specs.h [hunk 1]
```diff
@@ -113,17 +114,17 @@ typedef struct {
 #define PE_IMAGE_FILE_UP_SYSTEM_ONLY           0x4000
 #define PE_IMAGE_FILE_BYTES_REVERSED_HI        0x8000
 
-#define IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA        0x0020
+#define IMAGE_DLL_CHARACTERISTICS_HIGH_ENTROPY_VA        0x0020
```
Comment (wesinator) [inline libr/bin/format/pe/pe_specs.h]: I think these should be done in  separate commit or PR

File: libr/bin/format/pe/pe_specs.h [hunk 2]
```diff
@@ -66,6 +66,8 @@ typedef struct {
 #define PE_IMAGE_FILE_MACHINE_AM33             0x01d3
 #define PE_IMAGE_FILE_MACHINE_AMD64            0x8664
 #define PE_IMAGE_FILE_MACHINE_ARM              0x01c0
+#define PE_IMAGE_FILE_MACHINE_THUMB            0x01c2
+#define PE_IMAGE_FILE_MACHINE_RPI2             0x01c4
```
Comment (wesinator) [inline libr/bin/format/pe/pe_specs.h]: 0x01c4 is for ARMv7 / Thumb 2 ISA

do we actually know if the RPi2 Windows platform used this machine type, or 462 / `0x1ce` as per the comments in 26dd53e?

I think it might be good to label the 01c4 machine type as armv7 or thumb2, per https://learn.microsoft.com/windows/win32/debug/pe-format

File: libr/bin/format/pe/pe_specs.h (hunk 1 above)
Comment (trufae) [reply libr/bin/format/pe/pe_specs.h]: Agree. I just find out lots of things to improve and fix in the pe parser so i guess i’ll spend some time in here

File: libr/bin/format/pe/pe_specs.h (hunk 2 above)
Comment (trufae) [reply libr/bin/format/pe/pe_specs.h]: I think is better to use the very same names as the documentation mentions. But yep this is clearly thumb2 and even if that was used for rpi2 we may adjust it to use this name.

there are a bunch of new defines for the latest arm64 and loongarch cpus that mist be added too
