### PR TITLE
Fix memleak in fs_zip.c

### LINKED ISSUE #21293: Potential memory leak in libr/fs/p/fs_zip.c
Potential memory leak in [fs_zip.c](https://github.com/radareorg/radare2/blob/master/libr/fs/p/fs_zip.c) line 129. Calling zip_source_buffer_create() without calling zip_source_free() to free the memory will cause a memory leak. [Doc](https://libzip.org/documentation/zip_source.html) says "[zip_source_free(3)](https://libzip.org/documentation/zip_source_free.html) only needs to be called when these functions ([zip_open_from_source](https://libzip.org/documentation/zip_open_from_source.html)) return an error."
image

### PR DESCRIPTION
**Pull request by icy17**
Fix potential memleak in [fs_zip.c](https://github.com/radareorg/radare2/blob/master/libr/fs/p/fs_zip.c) line 129.
Fix #21293

### CODE REVIEW

File: libr/fs/p/fs_zip.c [hunk 1]
```diff
@@ -135,6 +135,8 @@ static RList *fs_zip_dir(RFSRoot *root, const char *path, R_UNUSED int view) {
 	zip_t *za = zip_open_from_source (zs, _flags, &error);
 	if (!za) {
 		R_LOG_ERROR ("failed to open zip from source");
+		// free zip_source if zip_open_from_source return an error.
+		zip_source_free(zs);
```
Comment (trufae) [inline libr/fs/p/fs_zip.c:139]:
```suggestion
		zip_source_free (zs);
```

File: libr/fs/p/fs_zip.c [hunk 2]
```diff
@@ -135,6 +135,8 @@ static RList *fs_zip_dir(RFSRoot *root, const char *path, R_UNUSED int view) {
 	zip_t *za = zip_open_from_source (zs, _flags, &error);
 	if (!za) {
 		R_LOG_ERROR ("failed to open zip from source");
+		// free zip_source if zip_open_from_source return an error.
```
Comment (trufae) [inline libr/fs/p/fs_zip.c:138]:
```suggestion
```

**Review by trufae — APPROVED** [review]
