### PR TITLE
DWARF - OOB read and multiple incorrect parsing fixes

### LINKED ISSUE #17304: OOB read in parse_ext_opcode DWARF code
@HoundThe by the way, when I open the attached file with ASAN enabled there is a violation in DWARF code, please take a look:
```
[i] ℤ ASAN_OPTIONS=detect_odr_violation=0 r2 test                                                                                                                                                                                  10:55:22 
=================================================================
==1136700==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6270000308fb at pc 0x7f4d9788fa15 bp 0x7fff35f67560 sp 0x7fff35f67550
READ of size 1 at 0x6270000308fb thread T0
    #0 0x7f4d9788fa14 in parse_ext_opcode /home/radare/radare2/libr/bin/dwarf.c:698
    #1 0x7f4d978935f2 in parse_opcodes /home/radare/radare2/libr/bin/dwarf.c:970
    #2 0x7f4d97893f13 in parse_line_raw /home/radare/radare2/libr/bin/dwarf.c:1048
    #3 0x7f4d978a5d69 in r_bin_dwarf_parse_line /home/radare/radare2/libr/bin/dwarf.c:2198
    #4 0x7f4d99d63726 in bin_dwarf /home/radare/radare2/libr/core/cbin.c:919
    #5 0x7f4d99d8be19 in r_core_bin_info /home/radare/radare2/libr/core/cbin.c:4100
    #6 0x7f4d99d57694 in r_core_bin_set_env /home/radare/radare2/libr/core/cbin.c:220
    #7 0x7f4d99c5721c in r_core_file_do_load_for_io_plugin /home/radare/radare2/libr/core/cfile.c:441
    #8 0x7f4d99c59b39 in r_core_bin_load /home/radare/radare2/libr/core/cfile.c:651
    #9 0x7f4d91c262f4 in r_main_radare2 /home/radare/radare2/libr/main/radare2.c:1089
    #10 0x5579c8087713 in main /home/radare/radare2/binr/radare2/radare2.c:96
    #11 0x7f4d9107a041 in __libc_start_main (/lib64/libc.so.6+0x27041)
    #12 0x5579c80871ad in _start (/home/radare/radare2/binr/radare2/radare2+0x21ad)

0x6270000308fb is located 0 bytes to the right of 12283-byte region [0x62700002d900,0x6270000308fb)
allocated by thread T0 here:
    #0 0x7f4da1037837 in __interceptor_calloc (/lib64/libasan.so.6+0xb0837)
    #1 0x7f4d978a5be9 in r_bin_dwarf_parse_line /home/radare/radare2/libr/bin/dwarf.c:2183
    #2 0x7f4d99d63726 in bin_dwarf /home/radare/radare2/libr/core/cbin.c:919
    #3 0x7f4d99d8be19 in r_core_bin_info /home/radare/radare2/libr/core/cbin.c:4100
    #4 0x7f4d99d57694 in r_core_bin_set_env /home/radare/radare2/libr/core/cbin.c:220
    #5 0x7f4d99c5721c in r_core_file_do_load_for_io_plugin /home/radare/radare2/libr/core/cfile.c:441
    #6 0x7f4d99c59b39 in r_core_bin_load /home/radare/radare2/libr/core/cfile.c:651
    #7 0x7f4d91c262f4 in r_main_radare2 /home/radare/radare2/libr/main/radare2.c:1089
    #8 0x5579c8087713 in main /home/radare/radare2/binr/radare2/radare2.c:96
    #9 0x7f4d9107a041 in __libc_start_main (/lib64/libc.so.6+0x27041)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/radare/radare2/libr/bin/dwarf.c:698 in parse_ext_opcode
Shadow bytes around the buggy address:
  0x0c4e7fffe0c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4e7fffe0d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4e7fffe0e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4e7fffe0f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4e7fffe100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c4e7fffe110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00[03]
  0x0c4e7fffe120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4e7fffe130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4e7fffe140: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4e7fffe150: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4e7fffe160: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==1136700==ABORTING
```

_Originally posted by @XVilka in https://github.com/radareorg/radare2/issues/17300#issuecomment-659808022_

### PR DESCRIPTION
**Pull request by HoundThe**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Fixes #17304 and incorrect line information parsing of special opcode and standard const add pc opcode.

### CODE REVIEW

File: libr/bin/dwarf.c [hunk 1]
```diff
@@ -786,7 +786,7 @@ static const ut8 *parse_spec_opcode(
 		// line line-range information. move away
 		return NULL;
 	}
-	advance_adr = adj_opcode / hdr->line_range;
+	advance_adr = (adj_opcode / hdr->line_range) * hdr->min_inst_len;
```
Comment (ret2libc) [inline libr/bin/dwarf.c:789]: just to understand.. where does this `* min_inst_len` come from?

Comment (HoundThe) [reply libr/bin/dwarf.c:789]: From the dwarf standard, http://www.dwarfstd.org/doc/Dwarf3.pdf#page=111&zoom=100,0,0
