### PR TITLE
Fix #15073: Disambiguate using fcn addr also in meta.min rbtree

### LINKED ISSUE #15073: aaa results in segfault - reappeared
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | 5.2.0-kali2-amd64
| File format of the file you reverse      | ELF
| Architecture/bits of the file        | x86/64
| r2 -v     | radare2 4.0.0-git 22789 @ linux-x86-64 git.3.9.0-9-g31203f74d commit: 31203f74db1e86bef2f31316db8bd936609b9969 build: 2019-09-18__21:49:39
|g++ --version | g++ (Debian 9.2.1-4) 9.2.1 20190821

### Expected behavior
[0x00405320]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.

### Actual behavior
[0x00405320]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
WARNING: r_anal_fcn_tree_delete: check 'ret_min == ret_addr' failed
Segmentation fault

### Steps to reproduce the behavior 
[ex9.zip](https://github.com/radareorg/radare2/files/3629151/ex9.zip)

unzip ex9.zip
make
r2 ex9
aaa

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

File: libr/anal/fcn.c [hunk 1]
```diff
@@ -146,14 +146,17 @@ static int _fcn_tree_cmp(const void *a_, const RBNode *b_) {
 	const RAnalFunction *b = FCN_CONTAINER (b_);
 	set_meta_min_if_needed ((RAnalFunction *)a);
 	set_meta_min_if_needed ((RAnalFunction *)b);
-	ut64 from0 = a->meta.min, to0 = a->meta.min + a->_size,
-		from1 = b->meta.min, to1 = b->meta.min + b->_size;
+	ut64 from0 = a->meta.min, to0 = a->meta.min + a->_size, addr0 = a->addr,
+		from1 = b->meta.min, to1 = b->meta.min + b->_size, addr1 = b->addr;
```
Comment (radare) [inline libr/anal/fcn.c]: mmaybe more readable to have 2 lines starting with ut64 instead of abusing the comma here

**Comment by radare** [comment]
is this somehow fixing or altering the crash we are having related to rbtree?

**Comment by kazarmy** [comment]
if you mean the general case, then this should work even if basic blocks can be shared ... this doesn't fix #15004 though, which stalls at the `Analyze all flags starting with sym. and entry0 (aa)` phase
