### PR TITLE
Fix #23937 - fix rahash2 JSON ssdeep output ##json ##print

### LINKED ISSUE #23937: rahash2 JSON output prints a hex digest of an ssdeep hash instead of the correct hash
## Environment

```sh
Thu Jan 30 12:11:24 CST 2025
radare2 5.9.9 33457 @ darwin-arm-32
birth: git.5.9.8-323-gc2c06d1228 2025-01-30__12:09:52
commit: c2c06d12281742effcd0087df5335e0346b701d4
options: gpl -O2 cs:5 cl:2 make
Darwin arm64
```

## Description

As noted at the end of #23930, the `rahash2` JSON output includes the wrong `ssdeep` hash value. I'm splitting this bug into its own issue as the two bugs are technically separate yet similar in nature.

## Test

```
> rahash2 -a ssdeep /bin/ls
/bin/ls: 0x00000000-0x00025bff ssdeep: 1536:H8pLK/4eqcKc38iKDLyc3++TQbrIRKo5:cCvqcMLyvYGURKo

> rahash2 -a ssdeep -j /bin/ls
[{"name":"ssdeep","hash":"313533363a4838704c4b2f346571634b633338694b444c7963332b2b5451627249524b6f353a63437671634d4c7976594755524b6f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"}]
```

### PR DESCRIPTION
**Pull request by mattunleashed**
- [ x] Mark this if you consider it ready to merge
- [ x] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

This should be a straight-forward code change to ensure `> rahash2 -a ssdeep -j /path/to/bin` actually prints the correct `ssdeep` hash as expected.

This is my first PR. I believe I followed everything correctly and expect this to be good to go, but I'm happy to learn and make updates if needed. Specifically, I:
* Recompiled and tested the expected output locally
* Added a test and reran the `r2r` test suite. Everything finished and I didn't see my test throw an error but I was unclear on how to specifically confirm that my new test actually ran.

I tracked some of my analysis to identify the fix on my personal fork [here](https://github.com/mattunleashed/radare2/issues/1).

### CODE REVIEW

**Comment by trufae** [comment]
```
[main] CC rahash2.c
rahash2.c: In function ‘do_hash_print’:
rahash2.c:151:23: error: pointer targets in passing argument 3 of ‘pj_ks’ differ in signedness [-Werror=pointer-sign]
  151 |    pj_ks (pj, "hash", c);
      |                       ^
      |                       |
      |                       const uint8_t * {aka const unsigned char *}
In file included from /home/runner/work/radare2/radare2/libr/include/r_cons.h:10,
                 from /home/runner/work/radare2/radare2/libr/include/r_util/r_diff.h:6,
                 from /home/runner/work/radare2/radare2/libr/include/r_util.h:58,
                 from /home/runner/work/radare2/radare2/libr/include/r_io.h:7,
                 from rahash2.c:5:
/home/runner/work/radare2/radare2/libr/include/r_util/pj.h:70:11: note: expected ‘const char *’ but argument is of type ‘const uint8_t *’ {aka ‘const unsigned char *’}
   70 | R_API PJ *pj_ks(PJ *j, const char *k, const char *v);
      |           ^~~~~
cc1: all warnings being treated as errors
```

File: libr/main/rahash2.c [hunk 1]
```diff
@@ -147,7 +147,11 @@ static void do_hash_print(RHash *ctx, RahashOptions *ro, ut64 hash, int dlen, PJ
 	case 'j':
 		pj_o (pj);
 		pj_ks (pj, "name", hname);
-		do_hash_hexprint (c, dlen, ule, pj, rad);
+		if (hash & R_HASH_SSDEEP) {
+			pj_ks (pj, "hash", c);
```
Comment (trufae) [inline libr/main/rahash2.c:151]: i would suggest to print the hash as an array of numbers or an hexpair string (that's probably more common representation) you can use the `r_hex_bin2strdup` function which takes c and dlen and returns a heap allocated string that can be passed instead of c to the pjks

Comment (trufae) [reply libr/main/rahash2.c:151]: in that case..for ssdeep. this is actually a binary printable buffer.. so maybe asuming that its null terminated you can just cast it to (const char *)

Comment (trufae) [inline libr/main/rahash2.c:151]:
```suggestion
			pj_ks (pj, "hash", (const char *)c);
```

Comment (mattunleashed) [reply libr/main/rahash2.c]: Yup - found a similar cast [elsewhere](https://github.com/radareorg/radare2/blob/431be882e457dccd06ae905a871bafe8448f2b17/libr/crypto/hash/state.c#L69) so figured that was an acceptable option. I was hoping to wake up this morning and make that code change but thanks for the assist!
