### PR TITLE
Fix #16305 - UAF in @@@{r,i,s,S,b} as well as add some help for `oc`

### LINKED ISSUE #16305: stack variable should be initialized
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | rradare2 4.3.1 23909 @ linux-x86-64 git.4.3.1-1-ge55661b commit: e55661bd4c229b9095982675709bdd52e1b4c068 build: 2020-03-22__22:18:20

### Expected behavior
Handle input error
### Actual behavior
seg fault

### Steps to reproduce the behavior 
$ r2 -
[0x00000000]> ocm'@@@r
Cannot open file
Segmentation fault (core dumped)

### Additional Logs, screenshots, source-code,  configuration dump, ...
image

Due to the uninitialized variable `RList *list` in `cmd.c: r_core_cmd_foreach3()`
```
	case 'r': // @@@r
		{
			ut64 offorig = core->offset;
			for (i = 0; i < R_REG_TYPE_LAST; i++) {
				RRegItem *item;
				ut64 value;
				head = r_reg_get_list (dbg->reg, i);
				if (!head) {
					continue;
				}
				r_list_foreach (head, iter, item) { // Uninitialized RList* list sometimes would cause the execution to enter this loop, lead to a seg fault
```

### PR DESCRIPTION
**Pull request by radare**
This oneliner still segfaults:

$ r2 -c "ocm'@@@f:sym*" /bin/ls

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Fix crash because the core is recreated and all the references are broken, so anything that can call ocm' can lead to a crash. which is really painful to do. but will improve overall stability

**Test plan**

* ocm'@@@i
* ocm'@@@S
* ocm'@@@b

do we want tests for those?

**Closing issues**

#16305
...

### CODE REVIEW

File: libr/core/cmd.c [hunk 1]
```diff
@@ -4007,20 +4022,27 @@ R_API int r_core_cmd_foreach3(RCore *core, const char *cmd, char *each) { // "@@
 		}
 #endif
 		break;
-	case 's':
+	case 's': // XXX this command will crash when used with 'oc' (ocm'@@@s)
 		if (each[1] == 't') { // strings
 			list = r_bin_get_strings (core->bin);
 			RBinString *s;
```
Comment (ret2libc) [inline libr/core/cmd.c:4028]: unused var

File: libr/core/cmd.c [hunk 2]
```diff
@@ -4007,20 +4022,27 @@ R_API int r_core_cmd_foreach3(RCore *core, const char *cmd, char *each) { // "@@
 		}
 #endif
 		break;
-	case 's':
+	case 's': // XXX this command will crash when used with 'oc' (ocm'@@@s)
```
Comment (ret2libc) [inline libr/core/cmd.c:4025]: this `./binr/radare2/radare2 -c "ocm'@@@s" /bin/ls` does not segfault for me, even with ASAN.

File: libr/core/cmd.c [hunk 3]
```diff
@@ -4007,20 +4022,27 @@ R_API int r_core_cmd_foreach3(RCore *core, const char *cmd, char *each) { // "@@
...
 		if (each[1] == 't') { // strings
 			list = r_bin_get_strings (core->bin);
 			RBinString *s;
 			if (list) {
 				ut64 offorig = core->offset;
 				ut64 obs = core->blocksize;
+				RBinString *s;
+				RList *lost = r_list_newf (free);
 				r_list_foreach (list, iter, s) {
+					RBinString *bs = r_mem_dup (s, sizeof (RBinString));
```
Comment (ret2libc) [inline libr/core/cmd.c:4035]: it would be so cool to have refcounting in these cases :(

**Comment by radare** [comment]
ive fixed the @@@s one and i cant repro any other crash now

File: libr/core/cmd.c (hunk 2 above)
Comment (ret2libc) [reply libr/core/cmd.c:4023]: this pls

Comment (radare) [reply libr/core/cmd.c:4023]: because its fixed

File: libr/core/cmd.c (hunk 3 above)
Comment (radare) [reply libr/core/cmd.c:4032]: yes it will

**Comment by radare** [comment]
should be good to merge now
