### PR TITLE
Fix #16543 - bin.str.enc affects izz + ascii is now alias for latin1

### LINKED ISSUE #16543: Missing strings on iOS binary with izz
### Work environment
OS/arch/bits (mandatory) : Arch Linux x86_64
File format of the file you reverse (mandatory): Mach-O 64-bit arm64 executable
Architecture/bits of the file (mandatory): Arm64
r2 -v full output: radare2 4.3.1 0 @ linux-x86-64 git.4.3.1/ commit: unknown build: 2020-03-20__16:02:58

### Expected behavior
izz find all the strings of the binary

### Actual behavior
izz missed the 'encryptPassword:' string: 
r24
that is present both in "strings" command:
r26
and is shown also in the binary:
R21
r23

The string has not strange encoding. Is a simple ASCII string.

### Steps to reproduce the behavior 

-> r2 ipa://DemoHITB.ipa
-> aaa
-> e emu.str=true
-> aaa
-> izz~encryptPassword  # String 'encryptPassword:' is missing
1638 0x0004d016 0x10004d016 29  30                             ascii   +[LoginUtil encryptPassword:]
2409 0x00056ef0 0x100056ef0 29  30                             ascii   +[LoginUtil encryptPassword:]
-> s 0x100012fc4  # In the next three instruction you can see missing string 'encryptPassword:'
-> s 0x100029749  # In this location there is the missing string. The string view fail to print it correctly:
r22
but it is a simple string, as show in the HEX view:
r23

### Additional Logs, screenshots, source-code,  configuration dump, ...

[ipaBugRadare.zip](https://github.com/radareorg/radare2/files/4466122/ipaBugRadare.zip)

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This pr allows `bin.str.enc` to affect `izz` (though not `iz` for some reason), and `ascii` is now an alias for `latin1`.

**Test plan**

GitHubCI and AppVeyor are green.

**Closing issues**

Fixes #16543.

### CODE REVIEW

**Comment by kazarmy** [comment]
Can do `r2 -e bin.str.enc=ascii binary` if one wants the flags to match up.

File: libr/bin/bfile.c [hunk 1]
```diff
@@ -407,7 +407,23 @@ static void get_strings_range(RBinFile *bf, RList *list, int min, int raw, ut64
 			return;
 		}
 	}
-	string_scan_range (list, bf, min, from, to, -1, raw, section);
+	int type;
+	const char *enc = bf->rbin->strenc;
```
Comment (XVilka) [inline libr/bin/bfile.c:411]: What about extracting it into the separate function?

Comment (kazarmy) [reply libr/bin/bfile.c:411]: Could be done but right now the code is unique afaik. There's another code structure like it in disasm.c but the enum involved is different. Probably will merge the two enums when the need arises.

Comment (kazarmy) [reply libr/bin/bfile.c:411]: Also have to decide whether it's best for the encoding to be stored as a string or an enum.
