### PR TITLE
Fix #15264 - Implement AND and BIC instructions in the ARM64 assembler ##asm

### LINKED ISSUE #15264: Aarch64 - r2 is not able to assemble BIC instructions
## Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ArchLinux X86 64 bits
| File format of the file you reverse (mandatory)      | 
| Architecture/bits of the file (mandatory)            | Aarch64 (arm64)
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 23176 @ linux-x86-64 git.3.9.0-196-g76e825ad0 - commit: 76e825ad078930af41969ebb57d669ea6df5cc65 build: 2019-10-13__12:57:54

### Expected behavior
r2 assembles BIC instructions, like `BIC x12, x12, #0x3FF`

### Actual behavior
```bash
rasm2 -aarm -b64 "BIC, x12, x12, #0xf"
  Cannot assemble 'BIC, x12, x12, #0xf' at line 3
  invalid
```

### Steps to reproduce the behavior 
Use r2 or rasm2 for assembling.

### Additional Logs, screenshots, source-code,  configuration dump, ...

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0802a/BIC_log_shift.html

https://static.docs.arm.com/100898/0100/the_a64_Instruction_set_100898_0100.pdf (page 8)

### PR DESCRIPTION
**Pull request by trufae**
**Checklist**

- [x] Closing issues: #15264
- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

### CODE REVIEW

File: libr/asm/arch/arm/armass64.c [hunk 1]
```diff
@@ -624,6 +661,41 @@ if (op->operands[1].reg_type == ARM_REG64) {
 	return seq_data;
 }
 
+static ut32 and(ArmOp *op, bool is_bic) {
+	ut32 data = UT32_MAX;
+
+	// Reg types need to match
+	if (!(op->operands[0].reg_type == op->operands[1].reg_type)) {
```
Comment (trufae) [inline libr/asm/arch/arm/armass64.c:668]: op->operands[0].reg_type is dereferenced 4 times. just hold it in a variable at the begining.

File: libr/asm/arch/arm/armass64.c [hunk 2]
```diff
@@ -624,6 +661,41 @@ if (op->operands[1].reg_type == ARM_REG64) {
...
+	} else {
+		return UT32_MAX;
+	}
+
+	bool is64bit = op->operands[0].reg_type & ARM_REG64;
+
+	data |= op->operands[0].reg;
+	data |= op->operands[1].reg << 5;
+
+	ut32 imm;
```
Comment (trufae) [inline libr/asm/arch/arm/armass64.c:685]: simplify if with the ternary operator:

```c
ut32 imm2 = op->operands[2].immediate;
ut32 imm = decodeBitMaskWithSize (is_bic? ~imm2: imm2, is64bit? 64:32);
```

File: libr/asm/arch/arm/armass64.c (hunk 1 above)
Comment (trufae) [reply libr/asm/arch/arm/armass64.c:668]: for example: `ut32 op0_regtype = op->operands[0].reg_type;`

**Review by trufae — COMMENTED** [review]
Can't makr as "requeste changes" because it's my own PR :__

Awesome work!

**Comment by trufae** [comment]
[XX] db/asm/arm_64 <asm> bic x1, x2, 3

Fix the test with r2r -i
