### PR TITLE
Fix #15296 - *BSD builds

### LINKED ISSUE #15296: BSD builds are broken
```
p/io_ptrace.c:193:25: error: use of undeclared identifier 'PTRACE_GETSIGINFO'
        ret = r_io_ptrace (io, PTRACE_GETSIGINFO, pid, NULL, &sig);
                               ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

File: libr/io/p/io_ptrace.c [hunk 1]
```diff
@@ -178,6 +178,14 @@ static bool __plugin_open(RIO *io, const char *file, bool many) {
 	return false;
 }
 
+static inline bool is_pid_already_attached (RIO *io, int pid, siginfo_t *sig) {
+#ifdef __linux__
+	-1 != r_io_ptrace (io, PTRACE_GETSIGINFO, pid, NULL, &sig);
```
Comment (ret2libc) [inline libr/io/p/io_ptrace.c]: return?

**Comment by XVilka** [comment]
For some reason it breaks the Linux debugger

**Comment by ret2libc** [comment]
It does not break Linux debugger. Master is already red for this. I think the test is wrong and I have submitted a pr to r2r
