### PR TITLE
Fix afs not showing types and args ##types

### LINKED ISSUE #16059: Changes to a function signature don't apply properly
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.0-git 23856 @ linux-x86-64 git.3.3.0-2767-g74d832d0b commit: 74d832d0b97dbc0973d5b480f1528b0bc601d140 build: 2020-02-26__13:49:00

### Expected behavior
`afs` should properly set return type and function parameters.

### Actual behavior
`afs` changes function name, but keeps type and function parameters from original signature definition.

### Steps to reproduce the behavior 
- Binary: ls (GNU coreutils) 8.31

```
~  $ r2 /bin/ls
[0x00005b10]> af
[0x00005b10]> afs
entry0 (int64_t arg3);
[0x00005b10]> "afs int foo.bar(int a, char *b);"
[0x00005b10]> afs
foo.bar (int64_t arg3);
[0x00005b10]>
```

### PR DESCRIPTION
**Pull request by oxcabe**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**
Removed some checks that unproperly trimmed the function name when trying to check if it existed in types SDB.
The `afs` code that prints the function signature should be refactored to just get the information straight from SDB (in this case, implementing `r_anal_fcn_to_string(RAnal, RAnalFunction)`, the same way it's done in zignature types to retrieve the information to generate them.

**Test plan**
Fixing currents tests that assumed the former behavior.

**Closing issues**
Fixes  #16059.

### CODE REVIEW

**Comment by oxcabe** [comment]
I guess it's just better to implement `r_anal_fcn_to_string(RAnal, RAnalFunction)`.

**Comment by radare** [comment]
Use getter syntax better

R_anal_function_get_name(fcn)

(Anal is linked to the fcn in fcn->anal

**Comment by radare** [comment]
Screenshot 2020-03-02 at 11 38 07

**Comment by XVilka** [comment]
Red still
```
[XX] db/cmd/types afs fcnname with dots  216
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -i /tmp/tmp-17118fAYHvOjuZCgh ../bins/elf/hello_world
af
afs
"afs foo.bar();"
afs
"afs char foo.bar(int a, ...);"
afs
 entry0 ();
-foo.bar ();
-foo.bar (int32_t a);
+int32_t foo.bar ();
+char foo.bar (int32_t a);
EXPECT='entry0 ();
int32_t foo.bar ();
char foo.bar (int32_t a);'
```

**Comment by oxcabe** [comment]
Will fix test in ~2hrs. I can't do it right now.

File: libr/anal/fcn.c [hunk 1]
```diff
@@ -1544,22 +1544,23 @@ R_API int r_anal_fcn_cc(RAnal *anal, RAnalFunction *fcn) {
...
+	RAnal *a = function->anal;
 	char *ret = NULL, *arg_i = NULL, *args = strdup ("");
 	// RList *args_list = r_list_newf ((RListFree) free);
 	unsigned int argc = 0, i, j;
 	const char *ret_type = sdb_const_get (a->sdb_types,
-	  r_str_newf ("func.%s.ret", fcn->name), 0);
+	  r_str_newf ("func.%s.ret", function->name), 0);
 	const char *argc_str = sdb_const_get (a->sdb_types,
-	  r_str_newf ("func.%s.args", fcn->name), 0);
+	  r_str_newf ("func.%s.args", function->name), 0);
```
Comment (radare) [inline libr/anal/fcn.c]: Tab vs spaces?

File: libr/anal/fcn.c [hunk 2]
```diff
@@ -1544,7 +1544,56 @@ R_API int r_anal_fcn_cc(RAnal *anal, RAnalFunction *fcn) {
...
+		ret = r_str_newf ("%s (%s);", function->name, args);
+	}
+
+	free (args);
+	return ret;
+}
+
+// TODO: replace instances of this function call with:
+// r_anal_function_get_name(RAnalFunction *function);
+R_API char *r_anal_fcn_to_string(RAnal *a, RAnalFunction *fcn) {
```
Comment (radare) [inline libr/anal/fcn.c]: THE VOID

File: libr/anal/fcn.c [hunk 3]
```diff
@@ -1544,7 +1544,56 @@ R_API int r_anal_fcn_cc(RAnal *anal, RAnalFunction *fcn) {
...
+		}
+		if (i + 1 == argc) {
+			args = r_str_newf ("%s%s", args, arg_i);
+		} else {
+			args = r_str_newf ("%s%s, ", args, arg_i);
+		}
+		free (arg_i);
+	}
+
+	if (ret_type) {
```
Comment (radare) [inline libr/anal/fcn.c]: Use ternary operator instead

File: test/new/db/cmd/types [hunk 4]
```diff
@@ -1476,7 +1476,7 @@ afs
 afs
 EOF
 EXPECT=<<EOF
-fcn.004e2420 (int64_t arg1, int64_t arg2, int64_t arg3, int64_t arg4, int64_t arg5, int64_t arg6, int64_t arg_8h);
```
Comment (radare) [inline test/new/db/cmd/types]: Is this. Orrect?

File: libr/anal/fcn.c (hunk 1 above)
Comment (radare) [reply libr/anal/fcn.c]: this  is leaking, nobody is freeing this r_str_newf, you can use sdb_fmt too. maybe we should add sdb_const_getf() that takes a format string as argument

Comment (radare) [reply libr/anal/fcn.c]: feedback on this @ret2libc ?

File: libr/anal/fcn.c [hunk 5]
```diff
@@ -1544,7 +1544,56 @@ R_API int r_anal_fcn_cc(RAnal *anal, RAnalFunction *fcn) {
...
+	const char *argc_str = sdb_const_get (a->sdb_types,
+	  r_str_newf ("func.%s.args", function->name), 0);
+
+	if (argc_str) {
+		argc = atoi (argc_str);
+	}
+
+	for (i = 0; i < argc; i++) {
+		arg_i = sdb_get (a->sdb_types,
+		  r_str_newf ("func.%s.arg.%d", function->name, i), 0);
```
Comment (radare) [inline libr/anal/fcn.c]: do not indent with spaces. make that thing fit in 1 line

File: libr/anal/fcn.c [hunk 6]
```diff
@@ -1544,7 +1544,56 @@ R_API int r_anal_fcn_cc(RAnal *anal, RAnalFunction *fcn) {
...
+		// parse commas
+		for (j = 0; j < strlen (arg_i); j++) {
+			if (arg_i[j] == ',') {
+				if (arg_i[j - 1] == '*') {
+					// remove whitespace
+					memmove (&arg_i[j], &arg_i[j + 1],
```
Comment (radare) [inline libr/anal/fcn.c]: same here

File: libr/anal/fcn.c [hunk 7]
```diff
@@ -1544,7 +1544,56 @@ R_API int r_anal_fcn_cc(RAnal *anal, RAnalFunction *fcn) {
...
+					  strlen (arg_i) - j);
+				} else {
+					arg_i[j] = ' ';
+				}
+			}
+		}
+		if (i + 1 == argc) {
```
Comment (radare) [inline libr/anal/fcn.c]: use ternary operator

File: libr/anal/fcn.c (hunk 1 above)
Comment (ret2libc) [reply libr/anal/fcn.c]: ok either way for me

File: test/new/db/cmd/types (hunk 4 above)
Comment (ret2libc) [reply test/new/db/cmd/types]: by looking a bit at the assembly, this change seems wrong, yeah

File: libr/anal/fcn.c (hunk 1 above)
Comment (oxcabe) [reply libr/anal/fcn.c]: Changed it since we also changed function name to `r_anal_function_get_name`

File: libr/anal/fcn.c (hunk 2 above)
Comment (oxcabe) [reply libr/anal/fcn.c]: Left that as it was because it really did break a lot of things

File: libr/anal/fcn.c (hunk 1 above)
Comment (oxcabe) [reply libr/anal/fcn.c]: > this is leaking, nobody is freeing this r_str_newf, you can use sdb_fmt too. maybe we should add sdb_const_getf() that takes a format string as argument

This would be great imho

File: test/new/db/cmd/types (hunk 4 above)
Comment (oxcabe) [reply test/new/db/cmd/types]: Yes, this is wrong, it's a bit weird because analyzing with `aaa` actually prints it with the arguments

File: libr/anal/fcn.c (hunk 6 above)
Comment (radare) [reply libr/anal/fcn.c]: use arg_i +j + i instead of&  []

Comment (oxcabe) [reply libr/anal/fcn.c]: done but I don't want to disturb travis right now

**Comment by XVilka** [comment]
Many broken tests

**Comment by radare** [comment]
Moving to 4.4

File: test/new/db/anal/x86_64 [hunk 8]
```diff
@@ -1132,8 +1132,8 @@ EXPECT=<<EOF
 |  | | |    0x00003cda      mov byte [rip + 0x1d33f], 1                ; [0x21020:1]=0
 | ========< 0x00003ce1      jmp 0x3cf9
 |  | | |    ; CODE XREF from main @ 0x3cb2
-|  | `----> 0x00003ce3      mov esi, 5                                 ; int64_t arg2
-|  |   |    0x00003ce8      xor edi, edi                               ; int64_t arg1
+|  | `----> 0x00003ce3      mov esi, 5
+|  |   |    0x00003ce8      xor edi, edi
```
Comment (radare) [inline test/new/db/anal/x86_64]: looks like a regression to me, but didnt chk the asm in detail

File: libr/anal/fcn.c [hunk 9]
```diff
@@ -1544,7 +1544,54 @@ R_API int r_anal_fcn_cc(RAnal *anal, RAnalFunction *fcn) {
 	return result;
 }
 
-R_API char *r_anal_fcn_to_string(RAnal *a, RAnalFunction *fs) {
+R_API char *r_anal_function_get_name(RAnalFunction *function) {
```
Comment (thestr4ng3r) [inline libr/anal/fcn.c]: `get_name` is not a good name for this. It would suggest something like just `return function->name;`. What about something like `get_signature`?

Comment (oxcabe) [reply libr/anal/fcn.c]: I agree with this, let me change it

File: libr/anal/fcn.c [hunk 10]
```diff
@@ -1544,7 +1544,54 @@ R_API int r_anal_fcn_cc(RAnal *anal, RAnalFunction *fcn) {
...
+		args = (i + 1 == argc)
+			? r_str_newf ("%s%s", args, arg_i)
+			: r_str_newf ("%s%s, ", args, arg_i);
+
+		free (arg_i);
+		free (sdb_arg_i);
+	}
+	ret = (ret_type)
+		? r_str_newf ("%s %s (%s);", ret_type, function->name, args)
+		: r_str_newf ("%s (%s);", function->name, args);;
```
Comment (radare) [inline libr/anal/fcn.c]: double ;;

File: test/new/db/anal/x86_64 [hunk 11]
```diff
@@ -1089,8 +1089,8 @@ EXPECT=<<EOF
...
```
Comment (radare) [inline test/new/db/anal/x86_64]: imho this is a regression

File: test/new/db/anal/x86_64 (hunk 8 above)
Comment (radare) [reply test/new/db/anal/x86_64]: what are the args discovered in fcn.00012740?

File: test/new/db/anal/x86_64 (hunk 11 above)
Comment (oxcabe) [reply test/new/db/anal/x86_64]: relevant: https://github.com/radareorg/radare2-regressions/pull/2007

**Comment by radare** [comment]
Ready to merge for me 👍
