### PR TITLE
Fix #16266 - Fix two warnings

### LINKED ISSUE #16266: fix warnings found on macos-travis
```
ld: warning: directory not found for option '-L../../cons'
4769/Users/travis/build/radareorg/radare2/libr/..//libr/bin/p/../format/elf/elf.c:3309:34: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
4770        return bin->shstrtab && sh_name >= 0 && sh_name < bin->shstrtab_size;
4771                                ~~~~~~~ ^  ~
47721 warning generated.
4773In file included from /Users/travis/build/radareorg/radare2/libr/..//libr/bin/p/../format/elf/elf64.c:4:
4774/Users/travis/build/radareorg/radare2/libr/..//libr/bin/p/../format/elf/elf.c:3309:34: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
4775        return bin->shstrtab && sh_name >= 0 && sh_name < bin->shstrtab_size;
4776                                ~~~~~~~ ^  ~
47771 warning generated.
4778/Users/travis/build/radareorg/radare2/libr/..//libr/bin/p/../format/mach0/mach0.c:3023:14: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
4779                if (amount < 0) {
4780                    ~~~~~~ ^ ~
47811 warning generated.
4782In file included from /Users/travis/build/radareorg/radare2/libr/..//libr/bin/p/../format/mach0/mach064.c:4:
4783/Users/travis/build/radareorg/radare2/libr/..//libr/bin/p/../format/mach0/mach0.c:3023:14: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
4784                if (amount < 0) {
4785                    ~~~~~~ ^ ~
47861 warning generated.
4787p/../arch/8051/8051_disas.c:64:14: warning: unused function 'r_8051_disas' [-Wunused-function]
4788static char *r_8051_disas(ut64 pc, const ut8 *buf, int len, int *olen) {
4789             ^
47901 warning generated.
4791/Users/travis/build/radareorg/radare2/libr/..//libr/anal/p/anal_arm_cs.c:1337:13: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
4792                if (shift < 0) {
4793                    ~~~~~ ^ ~
47941 warning generated.
4795/Users/travis/build/radareorg/radare2/libr/..//libr/anal/p/../..//asm/arch/tms320/c55x_plus/hashvector.c:97:25: warning: unused variable 'ins_hash' [-Wunused-variable]
4796static HASHCODE_ENTRY_T ins_hash[] = {
4797                        ^
47981 warning generated.
4799
4800
4801
```

### PR DESCRIPTION
**Pull request by radare**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

File: libr/bin/format/mach0/mach0.c [hunk 1]
```diff
@@ -3020,7 +3020,7 @@ RSkipList *MACH0_(get_relocs)(struct MACH0_(obj_t) *bin) {
 			return NULL;
 		}
 		ut64 amount = bind_size + lazy_size + weak_size;
-		if (amount < 0) {
+		if (amount == 0 || amount > UT32_MAX) {
```
Comment (XVilka) [inline libr/bin/format/mach0/mach0.c:3023]: Are you sure it requires to be 32bit number?

**Comment by radare** [comment]
No. Its just a reasonable boundary
