### PR TITLE
Fix x86 assembler accepting invalid register names like r1 ##asm

### LINKED ISSUE #25036: rasm2 Gives Wrong Output When Invalid Registers Are Involved
## Environment

```sh
Sun Dec 14 07:14:26 PM EET 2025
radare2 6.0.7 34644 @ linux-x86-64
birth: git.6.0.7-148-gdca8fb249c 2025-12-14__15:39:50
commit: dca8fb249c0d33ac4f0fdf280ecc0cdffbe19e79
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description

There are numerous examples, I'll list those I found:

The command ```rasm2 -a x86 'push rx'``` where x is any number besides 8-15 always yields "6a00"
for example: 
```sh
$ rasm2 -a x86 'push r9283293982'
6a00
```

The command ```rasm2 -a x86 'add rax, r1'``` outputs "4c01d0", which corresponds to ```addq %r10, %rax```

Likewise, ```rasm2 -a x86 'mov rax, r1'``` outputs the opcode for ```movq %r10, %rax```

```rasm2 -a x86 'lea rax, [r1]'``` outputs "488d02" which corresponds to ```leaq (%rdx), %rax```
```rasm2 -a x86 'xchg rax, r1'``` outputs "4992" which corresponds to ```xchgq %rax, %r10```
etc.
Generally, r1 is mistaken as some other register, most of the times, as r10, but there are exceptions.

## Test

Run any of the commands I supplied above, or use "r1" as a source or destination operand in rasm2 assembler.

### PR DESCRIPTION
**Pull request by 0verflowme**
The parseReg() function in x86_nz assembler used r_str_ncasecmp() with only the input token length, causing prefix matching. For example, 'r1' (length=2) would match the first 2 characters of 'r10', producing incorrect machine code.

Fix by adding strlen() check to ensure the register name length matches the token length exactly before comparing.

Fixes #25036

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

File: libr/arch/p/x86_nz/nzasm.c [hunk 1]
```diff
@@ -5488,7 +5488,7 @@ static Register parseReg(RArchSession *a, const char *str, size_t *pos, ut32 *ty
 	// General purpose registers
 	if (length == 3 && token[0] == 'e') {
 		for (i = 0; regs[i]; i++) {
-			if (!r_str_ncasecmp (regs[i], token, length)) {
+			if (strlen (regs[i]) == length && !r_str_ncasecmp (regs[i], token, length)) {
```
Comment (trufae) [inline libr/arch/p/x86_nz/nzasm.c]: maybe be better to avoid this repetitive pattern with a helper function like: 

```
static inline bool exactmatch(const char *reg, const char *token, size_t length) {
  return strlen (reg) == length && !r_str_ncasecmp (regs[i], token, length);
}
```

i want to assume the compiler can infer the constant length for the 2 and 3 blocks, but well there's more spaguetti to improve in this file :)

the patch looks good thanks!
