### PR TITLE
Fix #17418 leaks in ##signatures

### LINKED ISSUE #17418: Signature matching take so much memory that triggers oom killer
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch/x86/64 bits
| File format of the file you reverse (mandatory)      | PE(dll)
| Architecture/bits of the file (mandatory)            | x86/64 bits
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0 0 @ linux-x86-64 git.4.4.0 commit: unknown build: 2020-05-08__21:16:55

### Expected behavior
Not causing oom killer, finish matching

### Actual behavior
oom killer triggered

### Steps to reproduce the behavior 
[binary.tar.gz](https://github.com/radareorg/radare2/files/5042626/binary.tar.gz)
- r2 synaWudfBioUsb.dll
- aaa
- zo updated.sdb
- z/

### PR DESCRIPTION
**Pull request by swoops**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This fixes multiple leaks in `r_sign_deserialize` and `r_sign_item_free`. The `r_sign_deserialize` function will be more strict and skip over poorly formatted signatures, rather then try to parse them. When a signature is skipped because of poor formatting a descriptive error sent to stderr.

**Test plan**

`r2r ./db/tools/rasign2` and `r2r ./db/tools/rasign2` complete quickly, with no errors, on my system. 

I added a `#define` that may be considered ugly. If you don't like it, let me know how I can make it better.

**Closing issues**

closes #17418
~~There appears to be (I think) a minor leak in `r_sign_fcn_types` as called by `sign.c:typesMatchCB`. The leak can be avoided with `e sign.types = false`. I will create a separate issue for that. Even with the `typesMatchCB` leak I was able to complete the signature search with in a VM with limited memory without getting a out of memory error.~~
^^ Edit: Found and fixed leak so I did a quick rebase. I think that is all of them!

**Another issue?

Running the commands from the mentioned issue (use `e zign.bytes = false` for speed) will produce a lot of errors like:
```
<string>:1: error: identifier expected
<string>:1: error: ';' expected (got "180108870")
<string>:1: error: declaration expected
<string>:1: error: invalid number
<string>:1: error: declaration expected
<string>:1: error: invalid number
<string>:1: error: declaration expected
<string>:1: error: invalid number
<string>:1: error: declaration expected
<string>:1: error: invalid number
<string>:1: error: declaration expected
<string>:1: error: invalid number
<string>:1: error: declaration expected
<string>:1: error: invalid number
<string>:1: error: declaration expected
<string>:1: error: invalid number
...
```

These appear to be from `addFlag` calling down into `r_parse_c_string`. I don't know anything about that code, does that deserve an issue?

### CODE REVIEW

**Comment by XVilka** [comment]
can you show what string `r_parse_c_string` is trying to parse?

**Comment by himekifee** [comment]
Any update here? Waiting for it to be merged.

**Comment by swoops** [comment]
@XVilka I added some prettyness for the errors and I get stuff like:
```
=============== ERROR INFO ==============
ERR: 
<string>:1: error: exponent digits expected
<string>:1: error: declaration expected

-----------------------------------------
void 1800edc50(int64_t arg1, int64_t arg2, int64_t arg3, int64_t arg4, int64_t arg5, int64_t arg6, int64_t arg_18h, int64_t arg_28h, signed int64_t arg_30h, int64_t arg_38h);
+++++++++++++++++++++++++++++++++++++++++
```

While all the strings look about the same, the error varies between a couple things:
```
=============== ERROR INFO ==============
ERR: 
<string>:1: error: exponent digits expected
<string>:1: error: declaration expected

-----------------------------------------
void 1800edc50(int64_t arg1, int64_t arg2, int64_t arg3, int64_t arg4, int64_t arg5, int64_t arg6, int64_t arg_18h, int64_t arg_28h, signed int64_t arg_30h, int64_t arg_38h);
+++++++++++++++++++++++++++++++++++++++++

=============== ERROR INFO ==============                                                                                                                                                                                                      
ERR:                                                                                                                                                                                                                                           
<string>:1: error: identifier expected                                                                                                                                                                                                         
<string>:1: error: ';' expected (got "180010050")                                                                                                                                                                                              
<string>:1: error: declaration expected                                                                                                                                                                                                        
                                                                                                                                                                                                                                               
-----------------------------------------                                                                                                                                                                                                      
void 180010050(int64_t arg1, int64_t arg2, int64_t arg3, int64_t arg4, int64_t arg5, int64_t arg_8h, int64_t arg_10h, int64_t arg_18h, int64_t arg_20h, int64_t arg_28h);                                                                      
+++++++++++++++++++++++++++++++++++++++++

=============== ERROR INFO ==============                                                                                                                                                                                                      
ERR:                                                                                                                                                                                                                                           
<string>:1: error: identifier expected                                                                                                                                                                                                         
<string>:1: error: ';' expected (got "")                                                                                                                                                                                                       
<string>:1: error: declaration expected                                                                                                                                                                                                        
                                                                                                                                                                                                                                               
-----------------------------------------                                                                                                                                                                                                      
void 180114e50(int64_t arg1, int64_t arg2, int64_t arg3, int64_t arg4, int64_t arg5, int64_t arg6, int64_t arg7, int64_t arg8, int64_t arg_8h, int64_t arg_10h, int64_t arg_18h, int64_t arg_20h, int64_t arg_28h, int64_t arg_30h, int64_t arg
_38h, int64_t arg_40h, int64_t arg_48h, int64_t arg_50h);                                                                                                                                                                                      
                                                                                                                                                                                                      
```

Looks like the problem is because functions names start with a digit. This is an issue in `cmd_zign.c:__types_list_to_fcnstr`. That function has a few issues, so I hope to have a fix for it in a couple days.

**Comment by XVilka** [comment]
Yes, the number as a name is a problem - `shlr/tcc` supports only C naming for obvious reasons. So it's not a bug then. Can we use something like `sub_XXXX` or `fcn_XXX` instead?

File: libr/anal/sign.c [hunk 1]
```diff
@@ -77,26 +77,31 @@ R_API RList *r_sign_fcn_types(RAnal *a, RAnalFunction *fcn) {
...
-	char *args_expr = r_str_newf ("func.%s.args", fcn->name);
-	const char *ret_type = sdb_const_get (a->sdb_types, r_str_newf ("func.%s.ret", fcn->name), 0);
-	const char *fcntypes = sdb_const_get (a->sdb_types, args_expr, 0);
-	int argc = 0;
-	int i;
+	if (!ret) {
+		return NULL;
+	}
+
+	char *scratch = r_str_newf ("func.%s.args", fcn->name);
```
Comment (wargio) [inline libr/anal/sign.c:84]: maybe just fail when null?

File: libr/anal/sign.c [hunk 2]
```diff
@@ -77,26 +77,31 @@ R_API RList *r_sign_fcn_types(RAnal *a, RAnalFunction *fcn) {
...
+	const char *fcntypes = sdb_const_get (a->sdb_types, scratch, 0);
+	free (scratch);
+
+	scratch = r_str_newf ("func.%s.ret", fcn->name);
```
Comment (wargio) [inline libr/anal/sign.c:88]: maybe just fail when null?

**Comment by trufae** [comment]
Is 0x63837 a valid function name! Imho it shouldnt

**Comment by swoops** [comment]
> Is 0x63837 a valid function name! Imho it shouldnt

Yeah, that raises an important point. At what point did the function get named with a number? I think the `__types_list_to_fcnstr` function is mishandling strings and turning `fcn.00000000` into a function name of `00000000`. I make a second PR soon to try and fix this behavior.

**Comment by XVilka** [comment]
Thanks! Please address that naming issue in a separate PR.
