### PR TITLE
Fix for internal less and hud mode available while in non-interactive

### LINKED ISSUE #17677: Internal less and visual hud available while in non-interactive mode
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |  Arch Linux x64
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17284 @ darwin-x86-64 git.2.2.0-476-gf8cf84e06 commit: f8cf84e0653642d9ad34e760e0e56dd81860e799 build: 2018-02-17__11:08:27

### Expected behavior

Internal less and visual hud output modfiers to not be available while `e scr.interactive=false`

### Actual behavior

Internal less and visual hud is available

### Steps to reproduce the behavior 
```
r2 -
e scr.interactive=false
pd 10~..
```
And

```
r2 -
e scr.interactive=false
pd 10~...
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

Similar bug: [#16689](https://github.com/radareorg/radare2/issues/16689)

### PR DESCRIPTION
**Pull request by Emi1305**
mode

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

Interactive output modes - Internal less and hud - were available while `e scr.interactive=false`, which caused certain Cutter's console panel - And maybe other UIs - to hang.

**Test plan**

Test available at `test/db/cmd/cmd_interactive_modes`

**Closing issues**

Closes #17677 "

...

### CODE REVIEW

**Comment by karliss** [comment]
The fact that codecov reports 0% coverage for diff is a bit suspicious. It would be good to verify that the new test gets properly executed.

**Comment by karliss** [comment]
Indeed the test isn't written correctly.
```
[karlis@desktop1 test]$ r2r db/cmd/cmd_interactive_modes 
Running from /home/karlis/pr_os/radare2/test
Warning: found test tokens at the end of "/home/karlis/pr_os/radare2/test/db/cmd/cmd_interactive_modes" without RUN.
Loaded 0 tests.
[0/0]                       0 OK         0 BR        0 XX        0 FX
```

**Review by trufae — APPROVED** [review]

File: libr/cons/hud.c [hunk 1]
```diff
@@ -19,6 +19,10 @@ R_API char *r_cons_hud_file(const char *f) {
 // Display a buffer in the hud (splitting it line-by-line and ignoring
 // the lines starting with # )
 R_API char *r_cons_hud_string(const char *s) {
+	if (!r_cons_is_interactive ()) {
+		eprintf ("Hud mode requires scr.interactive=true.\n");
```
Comment (trufae) [inline libr/cons/hud.c:23]: i think its better to just return NULL here. and show this eprintf in the callers from core. because scr.interactive is core-specific, not related to RCons

**Review by trufae — CHANGES_REQUESTED** [review]

**Comment by trufae** [comment]
make it green

File: libr/cons/hud.c (hunk 1 above)
Comment (Emi1305) [reply libr/cons/hud.c:23]: I understand but both functions `r_cons_hud_string` and `r_cons_less_str` are called in multiple places (some of them not directly from the core):

```
$ grep -rn 'r_cons_hud_string (' 
libr/cons/less.c:85:			r_cons_hud_string (ostr);
libr/cons/grep.c:532:				r_cons_hud_string (cons->context->buffer);
libr/cons/grep.c:545:			char *res = r_cons_hud_string (buf);
libr/cons/more.c:81:			r_cons_hud_string (ostr);
libr/cons/hud.c:12:		char *ret = r_cons_hud_string (s);
```
```
$ grep -rn 'r_cons_less_str ('   
libr/cons/less.c:90:				(void)r_cons_less_str (r_cons_less_help, NULL);
libr/cons/less.c:169:	(void)r_cons_less_str (r_cons_singleton ()->context->buffer, NULL);
libr/cons/grep.c:535:				r_cons_less_str (cons->context->buffer, NULL);
libr/cons/grep.c:551:			r_cons_less_str (buf, NULL);
libr/cons/cons.c:903:				r_cons_less_str (str, NULL);
libr/core/cmd_log.c:233:					r_cons_less_str (b, NULL);
libr/core/visual.c:587:		ret = r_cons_less_str (r_strbuf_get (p), "?");
libr/core/visual.c:602:		ret = r_cons_less_str (r_strbuf_get (p), "?");
libr/core/visual.c:610:		ret = r_cons_less_str (r_strbuf_get (p), "?");
libr/core/visual.c:618:		ret = r_cons_less_str (r_strbuf_get (p), "?");
libr/core/visual.c:633:		ret = r_cons_less_str (r_strbuf_get (p), "?");
libr/core/visual.c:644:		ret = r_cons_less_str (r_strbuf_get (p), "?");
libr/core/visual.c:658:		ret = r_cons_less_str (r_strbuf_get (p), "?");
libr/core/visual.c:671:		ret = r_cons_less_str (r_strbuf_get (p), "?");
libr/core/visual.c:2088:		r_cons_less_str ("\nVisual Insert Mode:\n\n"
```

I think it would make the rest of the code messy

Apart from that both functions return `NULL` whether it succeeded or not and the return value is ignore in most if not all cases

Comment (trufae) [reply libr/cons/hud.c:23]: as long as the erroronly matters from core, i would say to make a wrapper of this function inside visual.c, just to show the error in case the function returns false. For the rest maybe its fine to just return silently. what do you think?

**Comment by trufae** [comment]
ping? can you make the visual wrapper function? lgtm after this

**Comment by Emi1305** [comment]
Sorry, I was afk until now. I'll give it a try

**Comment by Emi1305** [comment]
Apparently the calls we are looking for are not the ones made in `visual.c` but the ones made in `grep.c` the call chain is this:

cons.c: `r_cons_flush` -> cons.c: `r_cons_filter` -> grep.c: `r_cons_grepbuf` -> less.c: `r_cons_less_str`

`r_cons_flush` is called multiple times across the entire project:

```
test/unit/legacy_unit/cons/test-rgb.c:27:	r_cons_flush ();
test/unit/legacy_unit/cons/graph.c:95:	r_cons_flush ();
libr/cons/dietline.c:577:	r_cons_flush ();
libr/cons/dietline.c:627:	r_cons_flush ();
libr/cons/dietline.c:691:	r_cons_flush ();
libr/cons/dietline.c:898:                r_cons_flush ();
libr/cons/pager.c:71:	r_cons_flush ();
libr/cons/input.c:361:	r_cons_flush ();
libr/cons/input.c:406:	r_cons_flush ();
libr/cons/cons.c:1196:		r_cons_flush ();
libr/cons/hud.c:328:	r_cons_flush ();
libr/cons/2048.c:163:		r_cons_flush ();
libr/cons/2048.c:187:	r_cons_flush ();
libr/core/agraph.c:3269:	r_cons_flush ();
libr/core/agraph.c:3484:			r_cons_flush ();
libr/core/agraph.c:3542:			r_cons_flush ();
libr/core/agraph.c:3896:	r_cons_flush ();
libr/core/agraph.c:3922:	r_cons_flush ();
libr/core/agraph.c:3930:	r_cons_flush ();
libr/core/agraph.c:4084:	r_cons_flush ();
libr/core/cmd_help.c:534:		r_cons_flush ();
libr/core/cmd_help.c:1020:						  r_cons_flush ();
libr/core/cmd_help.c:1161:				r_cons_flush ();
libr/core/core.c:79:		r_cons_flush ();
libr/core/core.c:89:		r_cons_flush ();
libr/core/core.c:1690:				r_cons_flush ();
libr/core/core.c:2750:		r_cons_flush ();
libr/core/core.c:3004:	r_cons_flush ();
libr/core/vmenus_graph.c:377:			r_cons_flush ();
libr/core/p/core_java.c:1757:	r_cons_flush ();
libr/core/p/core_java.c:1784:	r_cons_flush ();
libr/core/rtr_shell.c:11:			r_cons_flush ();
libr/core/rtr_shell.c:31:			r_cons_flush ();
libr/core/rtr_shell.c:34:				r_cons_flush ();
libr/core/rtr_shell.c:67:				r_cons_flush ();
libr/core/rtr_shell.c:92:						r_cons_flush ();
libr/core/rtr_shell.c:125:							r_cons_flush ();
libr/core/rtr_shell.c:239:			r_cons_flush ();
libr/core/cmd_cmp.c:975:			r_cons_flush ();
libr/core/vmenus.c:245:			r_cons_flush ();
libr/core/vmenus.c:516:			r_cons_flush ();
libr/core/vmenus.c:821:			r_cons_flush ();
libr/core/vmenus.c:1312:			r_cons_flush ();
libr/core/vmenus.c:1521:			r_cons_flush ();
libr/core/vmenus.c:1658:		r_cons_flush ();
libr/core/vmenus.c:1671:		r_cons_flush ();
libr/core/vmenus.c:1703:			r_cons_flush ();
libr/core/vmenus.c:1723:				r_cons_flush ();
libr/core/vmenus.c:2128:			r_cons_flush ();
libr/core/vmenus.c:2264:			r_cons_flush ();
libr/core/vmenus.c:2302:			r_cons_flush ();
libr/core/vmenus.c:2464:			r_cons_flush ();
libr/core/vmenus.c:2583:		r_cons_flush ();
libr/core/vmenus.c:2608:						r_cons_flush ();
libr/core/vmenus.c:2615:						r_cons_flush ();
libr/core/vmenus.c:2627:							r_cons_flush ();
libr/core/vmenus.c:2632:						r_cons_flush ();
libr/core/vmenus.c:2657:						r_cons_flush ();
libr/core/vmenus.c:2769:					r_cons_flush ();
libr/core/vmenus.c:2789:				r_cons_flush ();
libr/core/vmenus.c:3168:	r_cons_flush ();
libr/core/vmenus.c:3184:	r_cons_flush ();
libr/core/vmenus.c:3341:			r_cons_flush ();
libr/core/vmenus.c:3712:	r_cons_flush ();
libr/core/vmenus.c:3799:	r_cons_flush ();
libr/core/vmenus.c:3821:			r_cons_flush ();
libr/core/vmenus.c:3922:				r_cons_flush ();
libr/core/vmenus.c:3978:				r_cons_flush ();
libr/core/vmenus.c:3998:				r_cons_flush ();
libr/core/vmenus.c:4315:		r_cons_flush ();
libr/core/cmd_search.c:2867:			r_cons_flush ();
libr/core/panels.c:809:	r_cons_flush ();
libr/core/panels.c:815:	r_cons_flush ();
libr/core/panels.c:822:	r_cons_flush ();
libr/core/panels.c:1291:	r_cons_flush ();
libr/core/panels.c:2193:			r_cons_flush ();
libr/core/panels.c:2201:			r_cons_flush ();
libr/core/panels.c:3468:		r_cons_flush ();
libr/core/panels.c:3484:	r_cons_flush ();
libr/core/panels.c:3522:	r_cons_flush ();
libr/core/panels.c:4948:			r_cons_flush ();
libr/core/panels.c:4977:			r_cons_flush ();
libr/core/panels.c:5106:	r_cons_flush ();
libr/core/panels.c:6024:	r_cons_flush ();
libr/core/panels.c:6468:	r_cons_flush ();
libr/core/cmd_anal.c:6539:			r_cons_flush ();
libr/core/cmd_anal.c:8354:					r_cons_flush ();
libr/core/cmd_anal.c:8445:						r_cons_flush ();
libr/core/cmd_anal.c:8712:					r_cons_flush ();
libr/core/rtr.c:103:	r_cons_flush ();
libr/core/rtr.c:921:		r_cons_flush ();
libr/core/vmenus_zigns.c:151:			r_cons_flush ();
libr/core/vasm.c:68:	r_cons_flush ();
libr/core/project.c:598:		r_cons_flush ();
libr/core/project.c:605:		r_cons_flush ();
libr/core/project.c:611:		r_cons_flush ();
libr/core/project.c:616:		r_cons_flush ();
libr/core/project.c:618:		r_cons_flush ();
libr/core/project.c:623:		r_cons_flush ();
libr/core/project.c:686:		r_cons_flush ();
libr/core/project.c:693:		r_cons_flush ();
libr/core/project.c:701:		r_cons_flush ();
libr/core/project.c:706:		r_cons_flush ();
libr/core/project.c:710:		r_cons_flush ();
libr/core/project.c:715:		r_cons_flush ();
libr/core/project.c:717:		r_cons_flush ();
libr/core/project.c:721:		r_cons_flush ();
libr/core/project.c:725:		r_cons_flush ();
libr/core/project.c:729:		r_cons_flush ();
libr/core/project.c:733:		r_cons_flush ();
libr/core/project.c:738:		r_cons_flush ();
libr/core/project.c:745:		r_cons_flush ();
libr/core/project.c:750:		r_cons_flush ();
libr/core/cmd_log.c:82:		r_cons_flush ();
libr/core/cmd.c:1563:				r_cons_flush ();
libr/core/cmd.c:2510:				r_cons_flush ();
libr/core/cmd.c:2742:			r_cons_flush ();
libr/core/cmd.c:2926:					r_cons_flush ();
libr/core/cmd.c:2944:				r_cons_flush ();
libr/core/cmd.c:3014:			//r_cons_flush ();
libr/core/cmd.c:3208:				r_cons_flush ();
libr/core/cmd.c:3825:		r_cons_flush ();
libr/core/cmd.c:4228:			r_cons_flush ();
libr/core/cmd.c:4461:				r_cons_flush ();
libr/core/cmd.c:5128:		r_cons_flush ();
libr/core/cmd.c:5137:			r_cons_flush ();
libr/core/cmd.c:5738:		r_cons_flush ();
libr/core/cmd.c:5780:		r_cons_flush ();
libr/core/cmd.c:6005:		r_cons_flush ();
libr/core/cmd.c:6470:		r_cons_flush ();
libr/core/cmd.c:6485:		r_cons_flush ();
libr/core/cmd.c:6596:			r_cons_flush ();
libr/core/cmd.c:6825:			r_cons_flush ();
libr/core/cmd.c:6842:		r_cons_flush ();
libr/core/cmd.c:6939:	r_cons_flush ();
libr/core/cmd.c:6965:		r_cons_flush ();
libr/core/cmd_api.c:962:				r_cons_flush ();
libr/core/visual.c:394:	r_cons_flush ();
libr/core/visual.c:439:	r_cons_flush ();
libr/core/visual.c:511:		r_cons_flush ();
libr/core/visual.c:518:	r_cons_flush ();
libr/core/visual.c:575:	r_cons_flush ();
libr/core/visual.c:787:		r_cons_flush ();
libr/core/visual.c:1107:	r_cons_flush ();
libr/core/visual.c:1129:	r_cons_flush ();
libr/core/visual.c:1332:	r_cons_flush ();
libr/core/visual.c:1525:			r_cons_flush ();
libr/core/visual.c:1534:	r_cons_flush ();
libr/core/visual.c:1555:		r_cons_flush ();
libr/core/visual.c:2141:		r_cons_flush ();
libr/core/visual.c:2482:			r_cons_flush ();
libr/core/visual.c:2756:			r_cons_flush ();
libr/core/visual.c:3156:				r_cons_flush ();
libr/core/visual.c:3166:					r_cons_flush ();
libr/core/visual.c:3176:					r_cons_flush ();
libr/core/visual.c:3193:				r_cons_flush ();
libr/core/visual.c:3428:			r_cons_flush ();
libr/core/visual.c:3892:	r_cons_flush ();
libr/core/visual.c:3959:	r_cons_flush ();
libr/core/visual.c:3978:	r_cons_flush ();
libr/core/visual.c:4083:		r_cons_flush ();
libr/main/rabin2.c:429:				r_cons_flush ();
libr/main/rabin2.c:1083:			r_cons_flush ();
libr/main/rabin2.c:1189:	r_cons_flush ();
libr/main/rasign2.c:45:		r_cons_flush ();
libr/main/rasign2.c:128:		r_cons_flush ();
libr/main/radiff2.c:109:		r_cons_flush ();
libr/main/radiff2.c:578:		r_cons_flush ();
libr/main/radiff2.c:582:	r_cons_flush ();
libr/main/radiff2.c:679:		r_cons_flush ();
libr/main/radiff2.c:683:	r_cons_flush ();
libr/main/radiff2.c:1171:			r_cons_flush ();
libr/main/rafind2.c:114:				r_cons_flush ();
libr/main/radare2.c:255:			r_cons_flush ();
libr/main/radare2.c:263:		r_cons_flush ();
libr/main/radare2.c:428:		r_cons_flush ();
libr/main/radare2.c:583:				r_cons_flush ();
libr/main/radare2.c:739:		r_cons_flush ();
libr/main/radare2.c:906:				r_cons_flush ();
libr/main/radare2.c:1197:				r_cons_flush ();
libr/main/radare2.c:1224:			r_cons_flush ();
libr/main/radare2.c:1298:			r_cons_flush ();
libr/main/radare2.c:1345:		r_cons_flush ();
libr/main/radare2.c:1375:			r_cons_flush ();
libr/debug/p/debug_rap.c:55:	r_cons_flush ();
libr/debug/p/debug_native.c:290:	r_cons_flush ();
libr/debug/p/debug_native.c:348:			r_cons_flush ();
libr/debug/p/debug_native.c:360:			r_cons_flush ();
libr/debug/p/debug_native.c:368:			r_cons_flush ();
libr/debug/p/debug_native.c:378:			r_cons_flush ();
libr/debug/p/debug_native.c:390:			r_cons_flush ();
libr/debug/p/debug_native.c:400:			r_cons_flush ();
libr/debug/p/native/w32.c:429:			r_cons_flush ();
libr/debug/p/native/w32.c:481:			r_cons_flush ();
libr/debug/p/native/w32.c:489:			r_cons_flush ();
libr/debug/p/debug_io.c:127:	r_cons_flush ();
libr/debug/p/debug_io.c:135:	r_cons_flush ();
libr/lang/lang.c:260:		r_cons_flush ();
```

I think the best option is to move the check and the error message to the function `parse_grep_expression` in `grep.c` at the point where `grep->less` and/or `grep->hud` are set and prevent it there, f.e.:

```
	while (*str) {
		switch (*str) {
		case '.':
			if (str[1] == '.') {
				if (str[2] == '.') {
					grep->less = 2;
				} else {
                                        if (!r_cons_is_interactive()) {
                                             eprintf ("Internal less requires scr.interactive=true.\n");
                                             return;
                                        }
					grep->less = 1;
				}
				return;
			}
			str++;
			break;
```
```

Another option would be to fail silently in `r_cons_less_str`/`r_cons_hud_string` and add the error message in `grep.c` at the moment of printing as following:
```
	if (grep->less) {
		int less = grep->less;
		grep->less = 0;
		if (less == 2) {
                        if (!r_cons_is_interactive()) {
                                eprintf ("Hud mode requires scr.interactive=true.\n");
                        }
			char *res = r_cons_hud_string (buf);
			if (res) {
				r_cons_println (res);
				free (res);
			}
```

Is any of this option suitable for you?

**Comment by trufae** [comment]
Sounds like a good approach

**Comment by trufae** [comment]
i mean both options look good to me, probably the second one is the safest as long as its done right before doing the actual thing. Can you do the change?

thanks!

**Review by trufae — APPROVED** [review]

**Review by trufae — APPROVED** [review]
