### PR TITLE
Fix ELF R_X86_64_PLT32 relocation entries patching ##bin

### LINKED ISSUE #17583: R_X86_64_PLT32 relocation types in relocatable objects
I have a relocatable object ([attached](https://github.com/radareorg/radare2/files/5170656/test_2.zip)) with the following relocations:
```
$ readelf -r test_2.ko

Relocation section '.rela.init.text' at offset 0x940 contains 6 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000001  001b00000004 R_X86_64_PLT32    0000000000000000 __fentry__ - 4
000000000009  00060000000b R_X86_64_32S      0000000000000000 .rodata.str1.1 + 0
000000000011  001d00000004 R_X86_64_PLT32    0000000000000000 printk - 4
000000000018  001e0000000b R_X86_64_32S      0000000000000000 kmalloc_caches + 460
00000000001f  00060000000b R_X86_64_32S      0000000000000000 .rodata.str1.1 + d
000000000024  001d00000004 R_X86_64_PLT32    0000000000000000 printk - 4

Relocation section '.rela.exit.text' at offset 0x9d0 contains 2 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000004  00060000000b R_X86_64_32S      0000000000000000 .rodata.str1.1 + 16
00000000000c  001d00000004 R_X86_64_PLT32    0000000000000000 printk - 4

Relocation section '.rela__mcount_loc' at offset 0xa00 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000000  000400000001 R_X86_64_64       0000000000000000 .init.text + 0

Relocation section '.rela.gnu.linkonce.this_module' at offset 0xa18 contains 2 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000178  001c00000001 R_X86_64_64       0000000000000000 init_module + 0
000000000330  001a00000001 R_X86_64_64       0000000000000000 cleanup_module + 0
```
In Radare2:
```
[cpey@localhost kernel_module]$ r2 -e io.cache=true -A test_2.ko
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
 -- Your problems are solved in an abandoned branch somewhere
[0x0800007c]> ir
[Relocations]

vaddr      paddr      type   name
―――――――――――――――――――――――――――――――――
0x0800007c 0x00000178 ADD_64 init_module
0x080000a8 0x00000330 ADD_64 cleanup_module
0x080000ba 0x00000009 ADD_32 .rodata.str1.1
0x080000ba 0x0000001f ADD_32 .rodata.str1.1 + 0x0000000d
0x080000ba 0x00000004 ADD_32 .rodata.str1.1 + 0x00000016
0x08000b0f 0x00000001 ADD_32 __fentry__ - 0x08000081
0x08000b17 0x00000011 ADD_32 printk - 0x08000091
0x08000b17 0x00000024 ADD_32 printk - 0x080000a4
0x08000b17 0x0000000c ADD_32 printk - 0x080000b8
0x08000b1f 0x00000018 ADD_32 kmalloc_caches + 0x00000460


10 relocations

[0x0800007c]> s sym.test_init
[0x0800007c]> pdf
            ;-- section..text:
            ;-- section..init.text:
            ;-- reloc.init_module:
            ;-- .text:
            ;-- .init.text:
            ;-- init_module:
            ;-- rip:
┌ 44: sym.test_init ();
│           0x0800007c      e88e0a0000     call init_module            ; RELOC 64 init_module @ 0x0800007c ; [04] -r-x section size 44 named .init.text
│           0x08000081      55             push rbp
│           0x08000082      48c7c7ba0000.  mov rdi, reloc..rodata.str1.1 ; 0x80000ba ; "Hello World\n"
│           0x08000089      4889e5         mov rbp, rsp
│           0x0800008c      e87e0a0000     call __fentry__
│           0x08000091      48c7c67f0f00.  mov rsi, 0x8000f7f
│           0x08000098      48c7c7c70000.  mov rdi, str.val:__p        ; 0x80000c7 ; "val: %p\n"
│           0x0800009f      e86b0a0000     call __fentry__
│           0x080000a4      31c0           xor eax, eax
│           0x080000a6      5d             pop rbp
└           0x080000a7      c3             ret
```
Where **`call __fentry__`** should be **`call printk`**.

The problem lies in the fact that the printk relocations are of type R_X86_64_PLT32, together with the relocatable not having .plt section.

```
[0x0800007c]> iS
[Sections]

nth paddr        size vaddr       vsize perm name
―――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00000000    0x0 0x08000000    0x0 ----
1   0x00000040   0x24 0x08000040   0x24 -r-- .note.gnu.build_id
2   0x00000064   0x18 0x08000064   0x18 -r-- .note.Linux
3   0x0000007c    0x0 0x0800007c    0x0 -r-x .text
4   0x0000007c   0x2c 0x0800007c   0x2c -r-x .init.text
5   0x00000940   0x90 0x08000940   0x90 ---- .rela.init.text
6   0x000000a8   0x12 0x080000a8   0x12 -r-x .exit.text
7   0x000009d0   0x30 0x080009d0   0x30 ---- .rela.exit.text
8   0x000000ba   0x25 0x080000ba   0x25 -r-- .rodata.str1.1
9   0x000000df    0x8 0x080000df    0x8 -r-- mcount_loc
10  0x00000a00   0x18 0x08000a00   0x18 ---- .rela__mcount_loc
11  0x000000e7   0x7a 0x080000e7   0x7a -r-- .modinfo
12  0x00000161    0x0 0x08000161    0x0 -rw- .data
13  0x00000180  0x380 0x08000180  0x380 -rw- .gnu.linkonce.this_module
14  0x00000a18   0x30 0x08000a18   0x30 ---- .rela.gnu.linkonce.this_module
15  0x00000500    0x0 0x08000500    0x0 -rw- .bss
16  0x00000500   0x4a 0x08000500   0x4a ---- .comment
17  0x0000054a    0x0 0x0800054a    0x0 ---- .note.GNU_stack
18  0x00000550  0x2e8 0x08000550  0x2e8 ---- .symtab
19  0x00000838  0x104 0x08000838  0x104 ---- .strtab
20  0x00000a48   0xc7 0x08000a48   0xc7 ---- .shstrtab
```
When patching the relocation in **_patch_reloc** function from bin_elf.inc, we correctly get into the R_X86_64_PLT32 case being the address to be patched calculated according to L + A - P (line 838), where L should represent the PLT entry for the symbol, A the addend, and P the relocation offset. In this particular case, L is causing the trouble.
```
 733 static void _patch_reloc(ut16 e_machine, RIOBind *iob, RBinElfReloc *rel, ut64 S, ut64 B, ut64 L) {
 [...]
 795     case EM_X86_64: {
 796         int word = 0;
 797         switch (rel->type) {
 [...]
 836         case R_X86_64_PLT32:
 837             word = 4;
 838             val = L + A - P;
 839             break;
 840         case R_X86_64_RELATIVE:
 841             word = 8;
 842             val = B + A;
 843             break;
 844         default:
 845             //eprintf ("relocation %d not handle at this time\n", rel->type);
 846             break;
 847         }
 [...]
```
L is calculated in the variable **n_vaddr** in patch_relocs function (same file) in line 918, assigning it the address of the first relocated symbol **`__fentry__`** .
```
 873 static RList* patch_relocs(RBin *b) {
 874     r_return_val_if_fail (b, NULL);
 875     RList *ret = NULL;
 876     RBinReloc *ptr = NULL;
 877     RIOMap *g = NULL;
 878     HtUU *relocs_by_sym;
 879     RBinElfReloc *relcs = NULL;
 880     RBinInfo *info;
 881     ut64 size, offset = 0;
 882
 [...]
 883     RIO *io = b->iob.io;
 884     if (!io || !io->desc) {
 885         return NULL;
 886     }
 [...]
 907     void **it;
 908     r_pvector_foreach (&io->maps, it) {
 909         RIOMap *map = *it;
 910         if (map->itv.addr > offset) {
 911             offset = map->itv.addr;
 912             g = map;
 913         }
 914     }
 915     if (!g) {
 916         return NULL;
 917     }
 918     ut64 n_vaddr = g->itv.addr + g->itv.size;
 [...]
 947     for (i = 0; !relcs[i].last; i++) {
 948         ut64 sym_addr = 0;
 949
 [...]
 957         // TODO relocation types B, L
 958         _patch_reloc (bin->ehdr.e_machine, &b->iob, &relcs[i], sym_addr? sym_addr: vaddr, 0, n_vaddr);
 959         if (!(ptr = reloc_convert (bin, &relcs[i], n_vaddr))) {
 960             continue;
 961         }
```

The problem gets solved by using **sym_addr** in L instead of **n_vaddr** but a proper way to treat this case is needed.

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

See issue, it's well described.

**Test plan**

See https://github.com/radareorg/radare2-testbins/pull/49.

**Closing issues**

Closes #17583

### CODE REVIEW

**Comment by ret2libc** [comment]
Ok apparently it is not working well yet. Moving it back to draft :(

**Comment by XVilka** [comment]
See also https://github.com/radareorg/radare2/issues/17300 and https://github.com/radareorg/radare2/issues/17523.

**Comment by ret2libc** [comment]
> See also #17300 and #17523.

Very different problem.

File: libr/core/disasm.c [hunk 1]
```diff
@@ -1512,13 +1512,6 @@ static int handleMidFlags(RCore *core, RDisasmState *ds, bool print) {
 			} else if (!strncmp (fi->name, "str.", 4)) {
 				ds->midflags = R_MIDFLAGS_REALIGN;
 			} else if (!strncmp (fi->name, "reloc.", 6)) {
-				if (print) {
```
Comment (ret2libc) [inline libr/core/disasm.c:1515]: Not only it seems unnecessary because, as written in the comment, there is already a comment for relocations. But it is also wrong in some cases.

File: libr/core/disasm.c [hunk 2]
```diff
@@ -5075,8 +5068,10 @@ static char *ds_sub_jumps(RDisasmState *ds, char *str) {
 			name = fcn->name;
 		}
 	} else if (f) {
-		RBinReloc *rel;
-		rel = r_core_getreloc (ds->core, ds->analop.addr, ds->analop.size);
+		RBinReloc *rel = NULL;
+		if (!ds->core->bin->is_reloc_patched) {
```
Comment (ret2libc) [inline libr/core/disasm.c:5072]: @GustavoLCR I saw this was done by you in https://github.com/radareorg/radare2/pull/14587 to correctly show relocations when `-e io.cache=true` is not used. However, when that's used this causes issues because the relocations AFAIK change positions.

**Review by XVilka — APPROVED** [review]
