### PR TITLE
Fix #17186 - Fix unaligned PE section paddr

### LINKED ISSUE #17186: [PE32] Incorrect analysis: invalid instructions at entrypoint
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 10.04 x86_64
| File format of the file you reverse (mandatory)      | PE32
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24827 @ linux-x86-64 git.4.4.0-340-g765f2b6bd commit: 765f2b6bd4098b8e90e46a45c174a71099bc0d56 build: 2020-06-28__21:50:09

### Expected behavior

A payload packed with "UPack 0.39" starts execution at vaddr: 0x01001018.
Using r2, entrypoint should be at vaddr: 0x01001018.
Using r2, data at vaddr: 0x01001018 should be mapped to first instructions.

### Actual behavior

Using r2, entrypoint **is indeed** at vaddr: 0x01001018.
Using r2, data at vaddr: 0x01001018 **is not** mapped to first instructions.
First instructions are mapped to vaddr: 0x01001008 instead.

### Steps to reproduce the behavior

**Using r2 (incorrect analysis):**
- Download and unzip **packed binary** : [upack.zip](https://github.com/radareorg/radare2/files/4852440/upack.zip)
- `radare2 upack.bin`
```
# At entrypoint
px/4i @0x1001018
0x01001018   eip:
0x01001018                 0b01  or eax, dword [ecx]
0x0100101a                   4c  dec esp
0x0100101b                   6f  outsd dx, dword [esi]
0x0100101c                   61  popal

# but instructions are here
px/4i @0x1001008
0x01001008           beb0110001  mov esi, 0x10011b0
0x0100100d                   ad  lodsd eax, dword [esi]
0x0100100e                   50  push eax
0x0100100f               ff7634  push dword [esi + 0x34]
```

**Using IDA (correct analysis):**

### PR DESCRIPTION
**Pull request by GustavoLCR**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Closing issues**

Fixes #17186

### CODE REVIEW

**Comment by XVilka** [comment]
@GustavoLCR is it possible to add a simple testcase for this?

File: libr/bin/format/pe/pe.c [hunk 1]
```diff
@@ -3903,8 +3904,14 @@ static struct r_bin_pe_section_t* PE_(r_bin_pe_get_sections)(struct PE_(r_bin_pe
 							sections[j].name);
 				}
 			}
+			ut32 fa = bin->optional_header->FileAlignment;
+			if (fa && sections[j].paddr % fa) {
+				bprintf ("Warning: section %s not aligned to FileAlignment.\n", sections[j].name);
+				ut64 diff = sections[j].paddr % fa;
```
Comment (trufae) [inline libr/bin/format/pe/pe.c:3910]: This is computed twice, also make it const

File: libr/bin/format/pe/pe.c [hunk 2]
```diff
@@ -3903,8 +3904,14 @@ static struct r_bin_pe_section_t* PE_(r_bin_pe_get_sections)(struct PE_(r_bin_pe
 							sections[j].name);
 				}
 			}
+			ut32 fa = bin->optional_header->FileAlignment;
```
Comment (trufae) [inline libr/bin/format/pe/pe.c:3907]: Const
